/* Absolute UX fix v3 — o seletor do Story aponta para o último TREINO REAL salvo, não para rascunho vazio. */
(()=>{
 const KEY='meu_treino_reset_v1',VIEW='meu_treino_pending_view';
 const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"logs":{}}')}catch{return {logs:{}}}};
 const write=d=>localStorage.setItem(KEY,JSON.stringify(d));
 const fmt=s=>Math.floor(Math.max(0,s)/60)+':'+String(Math.floor(Math.max(0,s)%60)).padStart(2,'0');
 const num=v=>Number(String(v??'').replace(',','.'))||0;
 const meaningful=l=>!!l&&(num(l.duration)>0||num(l.calories)>0||num(l?.cardio?.duration)>0||num(l?.cardio?.calories)>0||Object.values(l.rows||{}).some(r=>Object.keys(r||{}).some(k=>/^kg\d+$/.test(k)&&num(r[k])>0)));
 function stopAll(){const d=read();let changed=false;for(const l of Object.values(d.logs||{})){if(l?.timerStartedAt){const start=Date.parse(l.timerStartedAt);const elapsed=Math.max(0,Math.floor((Date.now()-start)/1000)+Number(l.timerElapsed||0));l.timerElapsed=elapsed;l.duration=fmt(elapsed);delete l.timerStartedAt;l.completed=true;changed=true}}if(changed)write(d)}
 function onReports(){const app=document.getElementById('app');if(!app)return false;return /<h1[^>]*>Progressão<\/h1>/i.test(app.innerHTML)}
 function addStory(){if(!onReports()||document.getElementById('absoluteStoryCard2'))return;const logs=Object.values(read().logs||{}).filter(l=>l?.date&&meaningful(l)).sort((a,b)=>b.date.localeCompare(a.date));if(!logs.length)return;const latest=logs[0],el=document.createElement('section');el.id='absoluteStoryCard2';el.className='card';el.innerHTML='<h2>📸 Story do Instagram</h2><p class="muted">Gere uma arte vertical 1080×1920 para postar no Story.</p><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:end"><label style="flex:1;min-width:200px;font-size:11px;font-weight:800">DATA DO TREINO<input id="storyDate2" type="date" value="'+latest.date+'" style="display:block;width:100%;box-sizing:border-box;margin-top:5px;height:42px;border:1px solid #ccd5dd;border-radius:10px;padding:0 10px"></label><button id="storyBtn2" class="primary">📲 Postar no Instagram</button></div><div id="storyMsg2" class="muted" style="margin-top:8px">Escolha a data e toque no botão.</div>';app.appendChild(el)}
 document.addEventListener('click',e=>{const b=e.target?.closest?.('button');if(!b)return;const t=(b.textContent||'').replace(/\s+/g,' ').trim();if(t.includes('Salvar treino')){e.preventDefault();e.stopImmediatePropagation();stopAll();alert('✓ Treino salvo');location.reload();return}if(t.includes('Histórico')||t.includes('Relatórios')){const target=t.includes('Relatórios')?'Relatórios':'Histórico';stopAll();localStorage.setItem(VIEW,target);e.preventDefault();e.stopImmediatePropagation();location.reload()}},true);
 window.addEventListener('load',()=>setTimeout(()=>{const v=localStorage.getItem(VIEW);if(v){localStorage.removeItem(VIEW);if(typeof go==='function')go(v)}addStory()},500));setInterval(addStory,500);
})();