/* Absolute UX fix: story + timer finalization */
(function(){
  const KEY='meu_treino_reset_v1';
  const VIEWKEY='meu_treino_pending_view';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')||{logs:{}}}catch(e){return {logs:{}}}};
  const write=d=>{try{localStorage.setItem(KEY,JSON.stringify(d))}catch(e){}};
  const iso=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
  const fmt=s=>Math.floor(Math.max(0,s)/60)+':'+String(Math.floor(Math.max(0,s)%60)).padStart(2,'0');
  function finalizeAllTimers(){const d=read();let changed=false;Object.values(d.logs||{}).forEach(l=>{if(l&&l.timerStartedAt){const elapsed=Math.max(0,Math.floor((Date.now()-new Date(l.timerStartedAt).getTime())/1000)+Number(l.timerElapsed||0));l.timerElapsed=elapsed;l.duration=fmt(elapsed);delete l.timerStartedAt;l.completed=true;changed=true}});if(changed)write(d);return changed}
  function volume(l){let n=0;Object.values(l?.rows||{}).forEach(r=>{for(let s=0;s<20;s++){const kg=Number(r?.['kg'+s]),rp=Number(r?.['reps'+s]);if(kg>0&&rp>0)n+=kg*rp}});return n}
  function card(){if(document.getElementById('absoluteStoryCard'))return;if(!document.getElementById('app'))return;const txt=(document.body.innerText||'');if(!/Relatórios|Progressão/.test(txt))return;const d=read(),logs=Object.values(d.logs||{}).filter(l=>l?.date).sort((a,b)=>b.date.localeCompare(a.date));if(!logs.length)return;const latest=logs[0];const el=document.createElement('section');el.id='absoluteStoryCard';el.className='card';el.style.cssText='margin-top:16px';el.innerHTML='<h2>📸 Story do Instagram</h2><p class="muted">Crie uma arte vertical para postar no Story.</p><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:end"><label style="flex:1;min-width:200px;font-size:11px;font-weight:800">DATA DO TREINO<input id="absStoryDate" type="date" value="'+latest.date+'" style="display:block;width:100%;box-sizing:border-box;margin-top:5px;height:42px;border:1px solid #ccd5dd;border-radius:10px;padding:0 10px"></label><button id="absStoryBtn" class="primary">📲 Postar no Instagram</button></div><div id="absStoryMsg" class="muted" style="margin-top:8px">Escolha a data e toque em Postar no Instagram.</div>';document.getElementById('app').appendChild(el);document.getElementById('absStoryBtn').onclick=()=>makeStory();}
  async function makeStory(){const d=read(),date=document.getElementById('absStoryDate')?.value,l=Object.values(d.logs||{}).find(x=>x?.date===date);if(!l){alert('Não há treino salvo nessa data.');return}const c=l.cardio||{},kcal=Number(l.calories||0)+Number(c.calories||0),vol=volume(l);let temp='—';try{await new Promise((resolve,reject)=>navigator.geolocation?.getCurrentPosition(async p=>{try{const u='https://api.open-meteo.com/v1/forecast?latitude='+p.coords.latitude+'&longitude='+p.coords.longitude+'&current=temperature_2m';const r=await fetch(u);const j=await r.json();temp=(j.current?.temperature_2m!=null?Math.round(j.current.temperature_2m)+' °C':'—');resolve()}catch(e){reject(e)}},reject,{timeout:4000}))}catch(e){}const cn=document.createElement('canvas');cn.width=1080;cn.height=1920;const x=cn.getContext('2d');x.fillStyle='#f5f7fa';x.fillRect(0,0,1080,1920);x.fillStyle='#f2760a';x.fillRect(0,0,1080,28);x.fillStyle='#182431';x.font='800 58px Arial';x.fillText('MEU TREINO',70,150);x.font='600 28px Arial';x.fillStyle='#71808f';x.fillText('MUSCULAÇÃO • PROGRESSÃO',72,195);x.fillStyle='#182431';x.font='800 54px Arial';x.fillText(String(l.day||'TREINO'),70,350);x.font='700 30px Arial';x.fillStyle='#71808f';x.fillText(date.split('-').reverse().join('/'),72,400);const vals=[['⏱','TEMPO DE TREINO',l.duration||'—'],['🔥','CALORIAS',kcal?Math.round(kcal)+' kcal':'—'],['🏋️','PESO LEVANTADO',Math.round(vol).toLocaleString('pt-BR')+' kg'],['🌡','TEMPERATURA',temp]];let y=540;vals.forEach(v=>{x.fillStyle='#fff';x.roundRect(55,y,970,230,30);x.fill();x.fillStyle='#f2760a';x.font='52px Arial';x.fillText(v[0],95,y+80);x.fillStyle='#71808f';x.font='700 25px Arial';x.fillText(v[1],180,y+70);x.fillStyle='#182431';x.font='800 58px Arial';x.fillText(v[2],180,y+145);y+=260});x.fillStyle='#71808f';x.font='600 24px Arial';x.fillText('MEU TREINO • PROGRESSÃO',70,1810);cn.toBlob(async blob=>{const file=new File([blob],'meu-treino-story.png',{type:'image/png'});if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]})){try{await navigator.share({title:'Meu Treino',files:[file]});return}catch(e){}}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='meu-treino-story.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);document.getElementById('absStoryMsg').textContent='Imagem gerada. No celular, use Compartilhar para enviar ao Instagram.'},'image/png');}
  document.addEventListener('click',function(e){const b=e.target?.closest?.('button');if(!b)return;const t=(b.textContent||'').replace(/\s+/g,' ').trim();if(t.includes('Salvar treino')){e.preventDefault();e.stopImmediatePropagation();const d=read(),day=(window.current&&['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'].includes(window.current))?window.current:'Quarta',k=day+'|'+iso(),l=d.logs?.[k];if(l?.timerStartedAt){const elapsed=Math.max(0,Math.floor((Date.now()-new Date(l.timerStartedAt).getTime())/1000)+Number(l.timerElapsed||0));l.timerElapsed=elapsed;l.duration=fmt(elapsed);delete l.timerStartedAt;l.completed=true;write(d)}alert('✓ Treino salvo');location.reload();return false}
    if(t.includes('Histórico')||t.includes('Relatórios')){const target=t.includes('Relatórios')?'Relatórios':'Histórico';finalizeAllTimers();try{localStorage.setItem(VIEWKEY,target)}catch(e){}e.preventDefault();e.stopImmediatePropagation();location.reload();return false}
  },true);
  window.addEventListener('load',()=>{setTimeout(()=>{const pending=localStorage.getItem(VIEWKEY);if(pending){localStorage.removeItem(VIEWKEY);if(typeof window.go==='function')window.go(pending)}card()},300)});
  setInterval(card,500);
})();
