/* Absolute UX fix v2 */
(()=>{
 const KEY='meu_treino_reset_v1',VIEW='meu_treino_pending_view';
 const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"logs":{}}')}catch{return {logs:{}}}};
 const write=d=>localStorage.setItem(KEY,JSON.stringify(d));
 const fmt=s=>Math.floor(Math.max(0,s)/60)+':'+String(Math.floor(Math.max(0,s)%60)).padStart(2,'0');
 function stopAll(){const d=read();let changed=false;for(const l of Object.values(d.logs||{})){if(l?.timerStartedAt){const start=Date.parse(l.timerStartedAt);const elapsed=Math.max(0,Math.floor((Date.now()-start)/1000)+Number(l.timerElapsed||0));l.timerElapsed=elapsed;l.duration=fmt(elapsed);delete l.timerStartedAt;l.completed=true;changed=true}}if(changed)write(d)}
 function onReports(){const app=document.getElementById('app');if(!app)return false;return /<h1[^>]*>Progressão<\/h1>/i.test(app.innerHTML)}
 function volume(l){let v=0;for(const r of Object.values(l?.rows||{}))for(let s=0;s<20;s++){const k=Number(r?.['kg'+s]),p=Number(r?.['reps'+s]);if(k>0&&p>0)v+=k*p}return v}
 function addStory(){if(!onReports()||document.getElementById('absoluteStoryCard2'))return;const d=read(),logs=Object.values(d.logs||{}).filter(l=>l?.date).sort((a,b)=>b.date.localeCompare(a.date));if(!logs.length)return;const latest=logs[0],el=document.createElement('section');el.id='absoluteStoryCard2';el.className='card';el.innerHTML='<h2>📸 Story do Instagram</h2><p class="muted">Gere uma arte vertical 1080×1920 para postar no Story.</p><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:end"><label style="flex:1;min-width:200px;font-size:11px;font-weight:800">DATA DO TREINO<input id="storyDate2" type="date" value="'+latest.date+'" style="display:block;width:100%;box-sizing:border-box;margin-top:5px;height:42px;border:1px solid #ccd5dd;border-radius:10px;padding:0 10px"></label><button id="storyBtn2" class="primary">📲 Postar no Instagram</button></div><div id="storyMsg2" class="muted" style="margin-top:8px">Escolha a data e toque no botão.</div>';app.appendChild(el);el.querySelector('#storyBtn2').onclick=generate}
 async function generate(){const d=read(),date=document.getElementById('storyDate2').value,l=Object.values(d.logs||{}).find(x=>x?.date===date);if(!l)return alert('Não há treino salvo nessa data.');const c=l.cardio||{},kcal=Number(l.calories||0)+Number(c.calories||0),vol=volume(l);let temp='—';try{const pos=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{timeout:3500}));const u=`https://api.open-meteo.com/v1/forecast?latitude=${pos.coords.latitude}&longitude=${pos.coords.longitude}&current=temperature_2m`;const j=await (await fetch(u)).json();if(j.current?.temperature_2m!=null)temp=Math.round(j.current.temperature_2m)+' °C'}catch{}
 const c2=document.createElement('canvas');c2.width=1080;c2.height=1920;const x=c2.getContext('2d');x.fillStyle='#f4f6f8';x.fillRect(0,0,1080,1920);x.fillStyle='#f2760a';x.fillRect(0,0,1080,26);x.fillStyle='#17222d';x.font='800 64px Arial';x.fillText('MEU TREINO',70,145);x.fillStyle='#71808f';x.font='600 28px Arial';x.fillText('MUSCULAÇÃO • PROGRESSÃO',72,192);x.fillStyle='#17222d';x.font='800 52px Arial';x.fillText(l.day||'TREINO',70,340);x.fillStyle='#71808f';x.font='700 30px Arial';x.fillText(date.split('-').reverse().join('/'),72,390);const rows=[['⏱','TEMPO DE TREINO',l.duration||'—'],['🔥','CALORIAS',kcal?Math.round(kcal)+' kcal':'—'],['🏋️','PESO LEVANTADO',Math.round(vol).toLocaleString('pt-BR')+' kg'],['🌡','TEMPERATURA',temp]];let y=520;for(const [ico,label,val] of rows){x.fillStyle='#fff';x.roundRect(55,y,970,225,30);x.fill();x.fillStyle='#f2760a';x.font='50px Arial';x.fillText(ico,95,y+80);x.fillStyle='#71808f';x.font='700 24px Arial';x.fillText(label,180,y+68);x.fillStyle='#17222d';x.font='800 58px Arial';x.fillText(val,180,y+145);y+=255}x.fillStyle='#71808f';x.font='600 24px Arial';x.fillText('MEU TREINO • PROGRESSÃO',70,1810);c2.toBlob(async blob=>{const file=new File([blob],'meu-treino-story.png',{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({title:'Meu Treino',files:[file]});return}catch{}}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='meu-treino-story.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);document.getElementById('storyMsg2').textContent='Imagem gerada para compartilhar no Instagram.'},'image/png')}
 document.addEventListener('click',e=>{const b=e.target?.closest?.('button');if(!b)return;const t=(b.textContent||'').replace(/\s+/g,' ').trim();if(t.includes('Salvar treino')){e.preventDefault();e.stopImmediatePropagation();stopAll();alert('✓ Treino salvo');location.reload();return}if(t.includes('Histórico')||t.includes('Relatórios')){const target=t.includes('Relatórios')?'Relatórios':'Histórico';stopAll();localStorage.setItem(VIEW,target);e.preventDefault();e.stopImmediatePropagation();location.reload()}},true);
 window.addEventListener('load',()=>setTimeout(()=>{const v=localStorage.getItem(VIEW);if(v){localStorage.removeItem(VIEW);if(typeof go==='function')go(v)}addStory()},500));setInterval(addStory,500);
})();
