const SUPABASE_URL='https://uvujytjdafcyacawcirp.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable__mofqtls_ru76dDkIJbIew_G2f_wUKE';
const KEY='meu_treino_pro_v2';
const workouts={
Segunda:{icon:'🟢',title:'Pernas + Peito',ex:[['Abdominal máquina',3,'12–15'],['Pêndulo',4,'6–10'],['Cadeira extensora',3,'10–15'],['Stiff com barra ou halteres',3,'8–10'],['Supino inclinado com halteres',4,'8–10'],['Supino reto máquina',3,'8–12'],['Crucifixo máquina',2,'12–15']]},
Terça:{icon:'🔵',title:'Costas + Bíceps',ex:[['Barra fixa ou puxada neutra',4,'6–10'],['Remada articulada com apoio no peito',4,'8–12'],['Remada unilateral na polia',3,'10–12'],['PULLDOWN',3,'10–15'],['Rosca direta com barra W',3,'8–12'],['Rosca inclinada com halteres',3,'10–12'],['Rosca martelo com halteres',2,'10–12']]},
Quarta:{icon:'🟠',title:'Pernas + Ombros',ex:[['Abdominal máquina',3,'12–15'],['Leg press 45°',4,'8–12'],['Elevação pélvica',3,'8–12'],['Cadeira flexora bilateral',4,'8–12'],['Mesa flexora',3,'10–15'],['Desenvolvimento máquina',3,'8–10'],['Elevação lateral na polia',4,'10–15'],['Crucifixo inverso máquina',3,'12–15'],['Panturrilha em pé ou no leg press',4,'10–15']]},
Quinta:{icon:'🔴',title:'Peito + Tríceps',ex:[['Supino reto com barra',4,'6–10'],['Supino inclinado máquina',3,'8–12'],['Supino reto máquina',3,'8–12'],['Crossover de baixo para cima',2,'12–15'],['Tríceps francês unilateral na polia',3,'10–12'],['Tríceps barra V',3,'8–12'],['Tríceps testa com barra W',2,'10–12']]},
Sexta:{icon:'🟣',title:'Full Body + Pontos fracos',ex:[['Abdominal máquina',3,'12–15'],['Hack squat',3,'8–12'],['Flexora unilateral',3,'10–12'],['Remada baixa triângulo',3,'8–12'],['Puxada alta pronada',3,'8–12'],['Supino inclinado com halteres',3,'8–12'],['Elevação lateral',3,'12–15'],['Rosca Scott máquina',2,'10–12'],['Tríceps corda',2,'10–15'],['Panturrilha',4,'12–15']]}};
const sat=[['Elevação lateral',3,'12–15'],['Crucifixo inverso',3,'12–15'],['Rosca martelo',3,'10–12'],['Tríceps corda',3,'10–12'],['Panturrilha',4,'12–15']];
let data=JSON.parse(localStorage.getItem(KEY)||'null')||{logs:{}},current='Segunda',user=null,cloudReady=false,cloudTimer=null,sb=null,historyExercise='Pêndulo';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const today=()=>new Date().toISOString().slice(0,10); const key=(d,dt)=>d+'|'+dt; const dateBR=d=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'});
function status(t,on){const e=document.getElementById('cloudStatus');if(e){e.textContent=t;e.className='status '+(on?'on':'')}}
function localSave(){try{localStorage.setItem(KEY,JSON.stringify(data))}catch(e){}status(user&&cloudReady?'☁ Online • salvo':'☁ Offline/local',!!(user&&cloudReady))}
function ensure(k,day,date){if(!data.logs[k])data.logs[k]={day,date,rows:{},notes:''};return data.logs[k]}
function makeClient(){try{if(window.supabase){sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);return true}}catch(e){}return false}
async function cloudSaveLog(k){if(!user||!cloudReady||!sb||!data.logs[k])return;const l=data.logs[k];const {error}=await sb.from('workout_logs').upsert({user_id:user.id,log_key:k,day:l.day,workout_date:l.date,payload:l,updated_at:new Date().toISOString()},{onConflict:'user_id,log_key'});if(error){console.error(error);status('⚠ Erro ao salvar',false)}else status('☁ Online • salvo',true)}
function queue(k){clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>cloudSaveLog(k),450)}
async function cloudLoad(){if(!user||!sb)return;const {data:rows,error}=await sb.from('workout_logs').select('log_key,payload').order('workout_date',{ascending:false});if(error){console.error(error);cloudReady=false;status('⚠ Nuvem indisponível',false);return}cloudReady=true;const local={...data.logs};if(!rows.length&&Object.keys(local).length){for(const k of Object.keys(local))await cloudSaveLog(k)}else{for(const r of rows)if(r.payload)data.logs[r.log_key]=r.payload;for(const k of Object.keys(local))if(!rows.some(r=>r.log_key===k))await cloudSaveLog(k)}localSave();render()}
async function signUp(){const e=document.getElementById('email')?.value.trim(),p=document.getElementById('password')?.value||'';if(!e||p.length<6)return alert('Informe e-mail e senha com pelo menos 6 caracteres.');if(!sb)return alert('A conexão online ainda não carregou. Recarregue.');const {error}=await sb.auth.signUp({email:e,password:p});alert(error?error.message:'Conta criada. Se pedir confirmação, confirme o e-mail e depois entre.')}
async function signIn(){const e=document.getElementById('email')?.value.trim(),p=document.getElementById('password')?.value||'';if(!sb)return alert('A conexão online ainda não carregou. Recarregue.');const {data:r,error}=await sb.auth.signInWithPassword({email:e,password:p});if(error)return alert(error.message);user=r.user;status('☁ Conectando…',true);await cloudLoad()}
async function signOut(){if(sb)await sb.auth.signOut();user=null;cloudReady=false;status('☁ Offline/local',false);render()}
function authPage(){document.getElementById('app').innerHTML='<div class="card auth"><div style="font-size:42px">🏋️</div><h1>Meu Treino</h1><p>Seu diário de musculação, cargas, repetições e progressão.</p><input id="email" type="email" placeholder="Seu e-mail"><input id="password" type="password" placeholder="Senha (mínimo 6 caracteres)"><button class="loginbtn" onclick="signIn()">ENTRAR</button><button class="secondary" style="width:100%;margin-top:7px" onclick="signUp()">CRIAR CONTA</button></div>'}
function days(){return Object.keys(workouts).map(d=>'<button class="'+(current===d?'active':'')+'" onclick="go(\''+d+'\')">'+workouts[d].icon+'<small>'+d.slice(0,3).toUpperCase()+'</small></button>').join('')+'<button class="'+(current==='Sábado'?'active':'')+'" onclick="go(\'Sábado\')">🟣<small>SÁB</small></button>'}
function nav(){return '<div class="daystrip">'+days()+'</div>'}
function mainNav(){return '<div class="nav"><button class="'+(['Segunda','Terça','Quarta','Quinta','Sexta','Sábado'].includes(current)?'active':'')+'" onclick="go(current===\'Sábado\'?\'Sábado\':current)">🏋️ Treino</button><button class="'+(current==='Histórico'?'active':'')+'" onclick="go(\'Histórico\')">📈 Histórico</button><button class="'+(current==='Relatórios'?'active':'')+'" onclick="go(\'Relatórios\')">📊 Relatórios</button><button class="'+(current==='Dados'?'active':'')+'" onclick="go(\'Dados\')">⚙️ Dados</button></div>'}
function go(x){current=x;render()}
function setVal(k,i,s,f,v){const l=ensure(k,current,today());l.rows[i]??={};l.rows[i][f+s]=v;localSave();queue(k);suggest(k,i)}
function setObs(k,i,v){const l=ensure(k,current,today());l.rows[i]??={};l.rows[i].observation=v;localSave();queue(k)}
function setMetric(k,f,v){const l=ensure(k,current,today());l[f]=v;localSave();queue(k)}
function range(s){const m=s.match(/(\d+)[–-](\d+)/);return m?[+m[1],+m[2]]:[0,999]}
function lastExercise(day,name,before){const arr=Object.values(data.logs).filter(l=>l.day===day&&l.date<before).sort((a,b)=>b.date.localeCompare(a.date));for(const l of arr){const ex=(workouts[day]?.ex||sat).findIndex(x=>x[0]===name);if(ex>=0&&l.rows?.[ex])return l.rows[ex]}}
function suggest(k,i){const el=document.getElementById('s'+i);if(!el)return;const ex=(workouts[current]?.ex||sat)[i],r=data.logs[k]?.rows[i]||{},vals=Array.from({length:ex[1]},(_,s)=>Number(r['reps'+s])).filter(Boolean);if(!vals.length){el.innerHTML='';return}const [lo,hi]=range(ex[2]),avg=vals.reduce((a,b)=>a+b,0)/vals.length,last=lastExercise(current,ex[0],data.logs[k].date),lastVals=last?Array.from({length:ex[1]},(_,s)=>Number(last['reps'+s])).filter(Boolean):[];el.innerHTML=vals.length>=ex[1]&&avg>=hi&&(!lastVals.length||avg>=lastVals.reduce((a,b)=>a+b,0)/lastVals.length)?'<span class="up">⬆ PROGRESSÃO: pode subir a carga</span>':avg<lo?'<span class="down">↘ Abaixo da faixa: mantenha ou ajuste</span>':'<span class="keep">→ Dentro da faixa: mantenha a carga</span>'}
function exerciseCard(ex,i,k){const r=data.logs[k]?.rows[i]||{};let sets='';for(let s=0;s<ex[1];s++)sets+='<div class="setrow"><div class="setno">'+(s+1)+'</div><input class="field" type="number" step="0.5" placeholder="kg" value="'+esc(r['kg'+s]??'')+'" onchange="setVal(\''+k+'\','+i+','+s+',\'kg\',this.value)"><input class="field" type="number" placeholder="reps" value="'+esc(r['reps'+s]??'')+'" onchange="setVal(\''+k+'\','+i+','+s+',\'reps\',this.value)"></div>';return '<article class="exercise"><div class="exhead"><div><div class="exname">'+(i+1)+'. '+esc(ex[0])+'</div><div class="meta">'+ex[1]+' séries • faixa '+ex[2]+' reps</div></div><div class="tag">'+ex[2]+' REPS</div></div><div class="sets"><div class="sethead"><span>SÉRIE</span><span>CARGA (KG)</span><span>REPS</span></div>'+sets+'</div><textarea class="obs" rows="2" placeholder="Observação: técnica, falha, dor, execução..." onchange="setObs(\''+k+'\','+i+',this.value)">'+esc(r.observation||'')+'</textarea><div id="s'+i+'" class="suggest"></div></article>'}
function workout(){const ex=current==='Sábado'?sat:workouts[current].ex,d=today(),k=key(current,d),l=ensure(k,current,d);document.getElementById('app').innerHTML=mainNav()+'<section class="hero"><div class="eyebrow">Treino de hoje</div><h1>'+(workouts[current]?.icon||'🟣')+' '+(workouts[current]?.title||'Treino opcional')+'</h1><p>'+dateBR(d)+' • Registre carga e repetições de cada série.</p></section>'+nav()+'<div class="stats"><div class="stat"><span>Exercícios</span><b>'+ex.length+'</b></div><div class="stat"><span>Séries</span><b>'+ex.reduce((a,e)=>a+e[1],0)+'</b></div><div class="stat"><span>Tempo</span><b>'+esc(l.duration||'—')+'</b></div><div class="stat"><span>Esforço</span><b>'+(l.effort?esc(l.effort)+'/10':'—')+'</b></div></div><div class="exercise-grid">'+ex.map((e,i)=>exerciseCard(e,i,k)).join('')+'</div><section class="card"><div class="sectiontitle"><h3>📊 Dados do treino</h3></div><div class="metrics"><div><label>TEMPO</label><input placeholder="Ex.: 1h 05min" value="'+esc(l.duration||'')+'" onchange="setMetric(\''+k+'\',\'duration\',this.value)"></div><div><label>BPM MÉDIO</label><input type="number" placeholder="119" value="'+esc(l.avgBpm||'')+'" onchange="setMetric(\''+k+'\',\'avgBpm\',this.value)"></div><div><label>CALORIAS</label><input type="number" placeholder="507" value="'+esc(l.calories||'')+'" onchange="setMetric(\''+k+'\',\'calories\',this.value)"></div><div><label>ESFORÇO</label><select onchange="setMetric(\''+k+'\',\'effort\',this.value)"><option value="">RPE</option>'+Array.from({length:10},(_,i)=>'<option value="'+(i+1)+'" '+(String(l.effort)===String(i+1)?'selected':'')+'>'+(i+1)+'/10</option>').join('')+'</select></div></div><h3 style="font-size:13px;margin:16px 0 7px">📝 Observações gerais</h3><textarea class="notes" onchange="const x=ensure(\''+k+'\',\''+current+'\',\''+d+'\');x.notes=this.value;localSave();queue(\''+k+'\')" placeholder="Como foi o treino? Energia, pump, dores, desempenho...">'+esc(l.notes||'')+'</textarea><div class="actions"><button class="primary" onclick="window.print()">🖨️ Relatório</button><button class="danger" onclick="clearDay()">Limpar dia</button></div></section>';ex.forEach((_,i)=>suggest(k,i))}
function history(){const names=new Set();Object.values(workouts).forEach(w=>w.ex.forEach(e=>names.add(e[0])));sat.forEach(e=>names.add(e[0]));const opts=[...names].sort((a,b)=>a.localeCompare(b,'pt-BR')).map(n=>'<option '+(n===historyExercise?'selected':'')+'>'+esc(n)+'</option>').join('');const rows=[];Object.values(data.logs).forEach(l=>(workouts[l.day]?.ex||sat).forEach((e,i)=>{if(e[0]!==historyExercise||!l.rows?.[i])return;const r=l.rows[i],sets=[];for(let s=0;s<e[1];s++)if(r['kg'+s]!==undefined||r['reps'+s]!==undefined)sets.push('S'+(s+1)+': '+(r['kg'+s]||'—')+' kg × '+(r['reps'+s]||'—'));if(sets.length)rows.push({date:l.date,day:l.day,sets})}));rows.sort((a,b)=>b.date.localeCompare(a.date));document.getElementById('app').innerHTML=mainNav()+'<section class="hero"><div class="eyebrow">Progressão</div><h1>📈 Histórico de carga</h1><p>Veja exatamente o que você fez em cada treino e acompanhe sua evolução.</p></section><div class="card"><div class="sectiontitle"><h3>Exercício</h3></div><select class="select" onchange="historyExercise=this.value;history()">'+opts+'</select></div><div class="card"><div class="sectiontitle"><h3>'+esc(historyExercise)+'</h3><span class="tag">'+rows.length+' REGISTROS</span></div>'+(rows.length?rows.map(r=>'<div class="historyrow"><b>'+dateBR(r.date)+' — '+esc(r.day)+'</b><div class="chips">'+r.sets.map(s=>'<span class="chip">'+esc(s)+'</span>').join('')+'</div></div>').join(''):'<div class="empty">Ainda não há registros desse exercício.</div>')+'</div>'}
function report(){const logs=Object.values(data.logs).sort((a,b)=>b.date.localeCompare(a.date));let sessions=logs.length,sets=0,reps=0,volume=0;logs.forEach(l=>Object.values(l.rows||{}).forEach(r=>{for(const k in r)if(k.startsWith('reps')&&r[k]!== ''){const q=Number(r[k])||0;reps+=q;sets++;volume+=(Number(r[k.replace('reps','kg')])||0)*q}}));document.getElementById('app').innerHTML=mainNav()+'<section class="hero"><div class="eyebrow">Performance</div><h1>📊 Relatório</h1><p>Resumo do seu histórico de musculação.</p></section><div class="stats"><div class="stat"><span>Sessões</span><b>'+sessions+'</b></div><div class="stat"><span>Séries</span><b>'+sets+'</b></div><div class="stat"><span>Repetições</span><b>'+reps+'</b></div><div class="stat"><span>Volume</span><b>'+Math.round(volume).toLocaleString('pt-BR')+' kg</b></div></div><div class="card"><div class="sectiontitle"><h3>Treinos registrados</h3></div>'+(logs.length?logs.map(l=>'<div class="historyrow"><b>'+dateBR(l.date)+' — '+esc(l.day)+'</b><div class="meta">'+esc(l.duration||'Tempo não informado')+' • '+(l.avgBpm?esc(l.avgBpm)+' bpm':'BPM —')+' • '+(l.calories?esc(l.calories)+' kcal':'kcal —')+' • '+(l.effort?esc(l.effort)+'/10':'RPE —')+'</div></div>').join(''):'<div class="empty">Nenhum treino registrado ainda.</div>')+'</div>'}
function dataPage(){document.getElementById('app').innerHTML=mainNav()+'<section class="hero"><div class="eyebrow">Conta e segurança</div><h1>⚙️ Dados</h1><p>Seu treino fica salvo na nuvem e também como cópia local.</p></section><div class="card"><b>Conta</b><p style="color:var(--muted)">'+esc(user?.email||'não conectado')+'</p><div class="actions"><button class="primary" onclick="exportData()">⬇ Exportar backup</button><button class="secondary" onclick="document.getElementById(\'imp\').click()">⬆ Importar backup</button><input id="imp" type="file" accept=".json" hidden onchange="importData(this)"><button class="danger" onclick="signOut()">Sair</button></div></div>'}
function exportData(){const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='backup-meu-treino-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(inp){const f=inp.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{data=JSON.parse(r.result);localSave();if(user&&cloudReady)for(const k of Object.keys(data.logs))await cloudSaveLog(k);render();alert('Backup importado e sincronizado.')}catch(e){alert('Backup inválido.')}};r.readAsText(f)}
async function clearDay(){if(!confirm('Apagar o treino de hoje?'))return;const k=key(current,today());delete data.logs[k];localSave();if(user&&cloudReady&&sb)await sb.from('workout_logs').delete().eq('user_id',user.id).eq('log_key',k);render()}
function bottom(){const n=document.getElementById('footnav');if(!n)return;n.innerHTML='<button class="'+(['Segunda','Terça','Quarta','Quinta','Sexta','Sábado'].includes(current)?'active':'')+'" onclick="go(current===\'Histórico\'||current===\'Relatórios\'||current===\'Dados\'?\'Segunda\':current)">🏋️<br>Treino</button><button class="'+(current==='Histórico'?'active':'')+'" onclick="go(\'Histórico\')">📈<br>Histórico</button><button class="'+(current==='Relatórios'?'active':'')+'" onclick="go(\'Relatórios\')">📊<br>Relatório</button><button class="'+(current==='Dados'?'active':'')+'" onclick="go(\'Dados\')">⚙️<br>Dados</button>'}
function render(){if(!user){authPage();bottom();return}if(current==='Histórico')history();else if(current==='Relatórios')report();else if(current==='Dados')dataPage();else workout();bottom()}
function start(){makeClient();render();if(!sb){status('⚠ Serviço online indisponível — dados locais preservados',false);return}sb.auth.getSession().then(async({data:r})=>{user=r.session?.user||null;if(user){status('☁ Conectando…',true);await cloudLoad()}else render()}).catch(()=>{user=null;render()});sb.auth.onAuthStateChange((_event,session)=>{user=session?.user||null;if(user&&!cloudReady)cloudLoad();else if(!user){cloudReady=false;render()}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();