const SUPABASE_URL='https://uvujytjdafcyacawcirp.supabase.co';
const SUPABASE_KEY='sb_publishable__mofqtls_ru76dDkIJbIew_G2f_wUKE';
const LOCAL_KEY='meu_treino_reset_v1';
const CLOUD_PREFIX='resetv1|';
const workouts={
 Segunda:{icon:'🟢',title:'Pernas + Peito',ex:[['Abdominal máquina',3,'12–15'],['Pêndulo',4,'6–10'],['Cadeira extensora',3,'10–15'],['Stiff com barra ou halteres',3,'8–10'],['Supino inclinado com halteres',4,'8–10'],['Supino reto máquina',3,'8–12'],['Crucifixo máquina',2,'12–15']]},
 Terça:{icon:'🔵',title:'Costas + Bíceps',ex:[['Barra fixa ou puxada neutra',4,'6–10'],['Remada articulada com apoio no peito',4,'8–12'],['Remada unilateral na polia',3,'10–12'],['PULLDOWN',3,'10–15'],['Rosca direta com barra W',3,'8–12'],['Rosca inclinada com halteres',3,'10–12'],['Rosca martelo com halteres',2,'10–12']]},
 Quarta:{icon:'🟠',title:'Pernas + Ombros',ex:[['Abdominal máquina',3,'12–15'],['Leg press 45°',4,'8–12'],['Elevação pélvica',3,'8–12'],['Cadeira flexora bilateral',4,'8–12'],['Mesa flexora',3,'10–15'],['Desenvolvimento máquina',3,'8–10'],['Elevação lateral na polia',4,'10–15'],['Crucifixo inverso máquina',3,'12–15'],['Panturrilha em pé ou no leg press',4,'10–15']]},
 Quinta:{icon:'🔴',title:'Peito + Tríceps',ex:[['Supino reto com barra',4,'6–10'],['Supino inclinado máquina',3,'8–12'],['Supino reto máquina',3,'8–12'],['Crossover de baixo para cima',2,'12–15'],['Tríceps francês unilateral na polia',3,'10–12'],['Tríceps barra V',3,'8–12'],['Tríceps testa com barra W',2,'10–12']]},
 Sexta:{icon:'🟣',title:'Full Body + Pontos fracos',ex:[['Abdominal máquina',3,'12–15'],['Hack squat',3,'8–12'],['Flexora unilateral',3,'10–12'],['Remada baixa triângulo',3,'8–12'],['Puxada alta pronada',3,'8–12'],['Supino inclinado com halteres',3,'8–12'],['Elevação lateral',3,'12–15'],['Rosca Scott máquina',2,'10–12'],['Tríceps corda',2,'10–15'],['Panturrilha',4,'12–15']]}
};
const sat=[['Elevação lateral',3,'12–15'],['Crucifixo inverso',3,'12–15'],['Rosca martelo',3,'10–12'],['Tríceps corda',3,'10–12'],['Panturrilha',4,'12–15']];
let data=JSON.parse(localStorage.getItem(LOCAL_KEY)||'null')||{logs:{}};
let current='Segunda',user=null,sb=null,cloudReady=false,saveTimer=null,authBusy=false;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const today=()=>new Date().toISOString().slice(0,10);
const key=(day,date)=>day+'|'+date;
const dateBR=d=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'});
const days=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
function setStatus(text,on=false){const e=$('cloudStatus');if(e){e.textContent=text;e.className='status '+(on?'on':'')}}
function localSave(){try{localStorage.setItem(LOCAL_KEY,JSON.stringify(data))}catch(e){}setStatus(user&&cloudReady?'☁ Online • salvo':'☁ Offline/local',!!(user&&cloudReady))}
function ensure(k,day,date){if(!data.logs[k])data.logs[k]={day,date,rows:{},notes:'',duration:'',avgBpm:'',calories:'',effort:''};return data.logs[k]}
function exFor(day){return day==='Sábado'?sat:workouts[day].ex}
function initClient(){try{sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);return !!sb}catch(e){console.error(e);return false}}
async function init(){if(!initClient()){setStatus('☁ Offline/local');render();return}setStatus('☁ Verificando...',true);try{const {data:r}=await sb.auth.getSession();user=r?.session?.user||null}catch(e){console.error(e)}render();if(user)loadCloud();else setStatus('☁ Pronto para entrar')}
async function signIn(){if(authBusy)return;const email=$('email')?.value.trim(),password=$('password')?.value||'';if(!email||!password){alert('Preencha e-mail e senha.');return}if(!sb){alert('A conexão ainda não carregou. Recarregue a página.');return}authBusy=true;const btn=$('loginBtn');if(btn){btn.disabled=true;btn.textContent='ENTRANDO...'}setStatus('☁ Conectando...',true);try{const {data:r,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;user=r.user;cloudReady=false;render();setStatus('☁ Login OK • carregando dados...',true);await loadCloud()}catch(e){console.error(e);setStatus('☁ Pronto para entrar');alert(e?.message||'Não foi possível entrar. Verifique e-mail e senha.')}finally{authBusy=false;if(btn){btn.disabled=false;btn.textContent='ENTRAR'}}}
async function signUp(){const email=$('email')?.value.trim(),password=$('password')?.value||'';if(!email||password.length<6){alert('Informe um e-mail e uma senha com pelo menos 6 caracteres.');return}if(!sb){alert('A conexão ainda não carregou.');return}const {error}=await sb.auth.signUp({email,password});alert(error?error.message:'Conta criada. Se aparecer confirmação por e-mail, confirme e depois faça login.')}
async function signOut(){try{await sb?.auth.signOut()}catch(e){}user=null;cloudReady=false;current='Segunda';render();setStatus('☁ Pronto para entrar')}
async function loadCloud(){if(!user||!sb)return;try{const {data:rows,error}=await sb.from('workout_logs').select('log_key,payload').like('log_key',CLOUD_PREFIX+'%').order('workout_date',{ascending:false});if(error)throw error;cloudReady=true;for(const r of rows||[]){if(r.payload)data.logs[r.log_key.replace(CLOUD_PREFIX,'')]=r.payload}localSave();render()}catch(e){console.error('cloud load',e);cloudReady=false;setStatus('⚠ Nuvem indisponível • local salvo')}}
function queueSave(k){clearTimeout(saveTimer);saveTimer=setTimeout(()=>cloudSave(k),500)}
async function cloudSave(k){if(!user||!sb||!data.logs[k])return;try{const l=data.logs[k];const {error}=await sb.from('workout_logs').upsert({user_id:user.id,log_key:CLOUD_PREFIX+k,day:l.day,workout_date:l.date,payload:l,updated_at:new Date().toISOString()},{onConflict:'user_id,log_key'});if(error)throw error;cloudReady=true;setStatus('☁ Online • salvo',true)}catch(e){console.error('cloud save',e);cloudReady=false;setStatus('⚠ Salvo neste aparelho')}}
function save(k){localSave();queueSave(k)}
function setVal(k,i,s,f,v){const l=ensure(k,current,today());l.rows[i]??={};l.rows[i][f+s]=v;save(k)}
function setObs(k,i,v){const l=ensure(k,current,today());l.rows[i]??={};l.rows[i].observation=v;save(k)}
function setMetric(k,f,v){const l=ensure(k,current,today());l[f]=v;save(k);renderWorkoutOnly()}
function setNotes(k,v){const l=ensure(k,current,today());l.notes=v;save(k)}
function clearDay(){const k=key(current,today());if(!confirm('Limpar os registros de hoje deste treino?'))return;delete data.logs[k];localSave();render()}
function dayNav(){return '<div class="daystrip">'+days.map(d=>'<button class="'+(current===d?'active':'')+'" onclick="go(\''+d+'\')">'+(d==='Sábado'?'🟣':workouts[d].icon)+'<small>'+d.slice(0,3).toUpperCase()+'</small></button>').join('')+'</div>'}
function topNav(){return '<div class="nav"><button class="'+(days.includes(current)?'active':'')+'" onclick="go(\'Segunda\')">🏋️ Treino</button><button class="'+(current==='Histórico'?'active':'')+'" onclick="go(\'Histórico\')">📈 Histórico</button><button class="'+(current==='Relatórios'?'active':'')+'" onclick="go(\'Relatórios\')">📊 Relatórios</button><button class="'+(current==='Dados'?'active':'')+'" onclick="go(\'Dados\')">⚙️ Dados</button></div>'}
function bottomNav(){return '<div class="bottomnav"><button class="'+(days.includes(current)?'active':'')+'" onclick="go(\'Segunda\')">🏋️<span>Treino</span></button><button class="'+(current==='Histórico'?'active':'')+'" onclick="go(\'Histórico\')">📈<span>Histórico</span></button><button class="'+(current==='Relatórios'?'active':'')+'" onclick="go(\'Relatórios\')">📊<span>Relatórios</span></button><button class="'+(current==='Dados'?'active':'')+'" onclick="go(\'Dados\')">⚙️<span>Dados</span></button></div>'}
function go(x){current=x;render()}
function exerciseCard(ex,i,k){const r=data.logs[k]?.rows?.[i]||{};let sets='';for(let s=0;s<ex[1];s++)sets+='<div class="setrow"><div class="setno">'+(s+1)+'</div><input class="field" type="number" step="0.5" inputmode="decimal" placeholder="kg" value="'+esc(r['kg'+s]??'')+'" onchange="setVal(\''+k+'\','+i+','+s+',\'kg\',this.value)"><input class="field" type="number" inputmode="numeric" placeholder="reps" value="'+esc(r['reps'+s]??'')+'" onchange="setVal(\''+k+'\','+i+','+s+',\'reps\',this.value)"></div>';return '<article class="exercise"><div class="exhead"><div><div class="exname">'+(i+1)+'. '+esc(ex[0])+'</div><div class="meta">'+ex[1]+' séries • '+ex[2]+' reps</div></div><span class="tag">'+ex[2]+'</span></div><div class="sets"><div class="sethead"><span>SÉRIE</span><span>CARGA KG</span><span>REPS</span></div>'+sets+'</div><textarea class="obs" rows="2" placeholder="Observação: técnica, falha, dor, execução..." onchange="setObs(\''+k+'\','+i+',this.value)">'+esc(r.observation||'')+'</textarea></article>'}
function workout(){const ex=exFor(current),d=today(),k=key(current,d),l=ensure(k,current,d);return topNav()+'<section class="hero"><div class="eyebrow">Treino de hoje</div><h1>'+(workouts[current]?.icon||'🟣')+' '+(workouts[current]?.title||'Treino opcional')+'</h1><p>'+dateBR(d)+' • Registre carga, repetições e métricas.</p></section>'+dayNav()+'<div class="stats"><div class="stat"><span>Exercícios</span><b>'+ex.length+'</b></div><div class="stat"><span>Séries</span><b>'+ex.reduce((a,e)=>a+e[1],0)+'</b></div><div class="stat"><span>Tempo</span><b>'+esc(l.duration||'—')+'</b></div><div class="stat"><span>Calorias</span><b>'+esc(l.calories||'—')+'</b></div></div><div class="exercise-grid">'+ex.map((e,i)=>exerciseCard(e,i,k)).join('')+'</div><section class="card metricsCard"><h2>📊 Métricas do treino</h2><div class="metrics"><label>⏱️ TEMPO<input placeholder="1h 05min" value="'+esc(l.duration||'')+'" onchange="setMetric(\''+k+'\',\'duration\',this.value)"></label><label>❤️ BPM MÉDIO<input type="number" placeholder="119" value="'+esc(l.avgBpm||'')+'" onchange="setMetric(\''+k+'\',\'avgBpm\',this.value)"></label><label>🔥 CALORIAS<input type="number" placeholder="500" value="'+esc(l.calories||'')+'" onchange="setMetric(\''+k+'\',\'calories\',this.value)"></label><label>💪 ESFORÇO<select onchange="setMetric(\''+k+'\',\'effort\',this.value)"><option value="">RPE</option>'+Array.from({length:10},(_,i)=>'<option value="'+(i+1)+'" '+(String(l.effort)===String(i+1)?'selected':'')+'>'+(i+1)+'/10</option>').join('')+'</select></label></div><label class="noteslabel">📝 Observações gerais<textarea class="notes" rows="3" placeholder="Como foi o treino? Energia, desempenho, dores..." onchange="setNotes(\''+k+'\',this.value)">'+esc(l.notes||'')+'</textarea></label><div class="actions"><button class="primary" onclick="alert(\'Treino salvo.\')">✓ Salvar treino</button><button class="danger" onclick="clearDay()">Limpar hoje</button></div></section>'}
function renderWorkoutOnly(){if(days.includes(current)){$('app').innerHTML=workout()+bottomNav()}}
function history(){const logs=Object.values(data.logs).filter(l=>l.date).sort((a,b)=>b.date.localeCompare(a.date));if(!logs.length)return topNav()+'<section class="card empty"><div class="emptyicon">📈</div><h2>Nenhum treino registrado</h2><p>Depois que você registrar seu primeiro treino, ele aparecerá aqui.</p></section>';const rows=logs.map(l=>{const filled=Object.values(l.rows||{}).filter(r=>Object.keys(r||{}).length).length;return '<article class="historyrow"><div class="historyhead"><div><b>'+l.day+' — '+dateBR(l.date)+'</b><small>'+(workouts[l.day]?.title||'Treino opcional')+'</small></div><span>'+filled+' exercícios</span></div><div class="chips">'+(l.calories?'<span>🔥 '+esc(l.calories)+' kcal</span>':'')+(l.avgBpm?'<span>❤️ '+esc(l.avgBpm)+' bpm</span>':'')+(l.duration?'<span>⏱️ '+esc(l.duration)+'</span>':'')+(l.effort?'<span>💪 RPE '+esc(l.effort)+'</span>':'')+'</div></article>'}).join('');return topNav()+'<section class="hero compact"><div class="eyebrow">Histórico</div><h1>Seus registros</h1><p>Todos os treinos salvos neste aplicativo.</p></section><section class="card">'+rows+'</section>'}
function volumeForLog(l){let total=0;for(const r of Object.values(l.rows||{})){for(let s=0;s<10;s++){const kg=Number(r?.['kg'+s]),reps=Number(r?.['reps'+s]);if(kg>0&&reps>0)total+=kg*reps}}return total}
function reports(){const logs=Object.values(data.logs).filter(l=>l.date).sort((a,b)=>a.date.localeCompare(b.date));const recent=logs.slice(-10);const totalVolume=logs.reduce((a,l)=>a+volumeForLog(l),0);const totalKcal=logs.reduce((a,l)=>a+Number(l.calories||0),0);const bpms=logs.filter(l=>Number(l.avgBpm));const avgBpm=bpms.reduce((a,l)=>a+Number(l.avgBpm),0)/(bpms.length||1);const max=Math.max(...recent.map(volumeForLog),1);const bars=recent.map(l=>'<div class="barcol"><div class="barvalue">'+Math.round(volumeForLog(l))+'</div><div class="bar" style="height:'+Math.max(8,volumeForLog(l)/max*150)+'px"></div><small>'+new Date(l.date+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})+'</small></div>').join('');return topNav()+'<section class="hero compact"><div class="eyebrow">Relatórios</div><h1>Progressão</h1><p>Resumo dos seus registros e volume de treino.</p></section><div class="reportstats"><div class="stat"><span>Treinos</span><b>'+logs.length+'</b></div><div class="stat"><span>Volume total</span><b>'+Math.round(totalVolume).toLocaleString('pt-BR')+' kg</b></div><div class="stat"><span>Calorias</span><b>'+Math.round(totalKcal).toLocaleString('pt-BR')+'</b></div><div class="stat"><span>BPM médio</span><b>'+(bpms.length?Math.round(avgBpm):'—')+'</b></div></div><section class="card chartcard"><h2>📊 Volume por treino</h2><p class="muted">Últimos 10 treinos registrados.</p><div class="chart">'+(bars||'<div class="empty">Ainda não há dados suficientes.</div>')+'</div></section><section class="card"><h2>📋 Resumo recente</h2>'+(recent.slice().reverse().map(l=>'<div class="summaryrow"><b>'+l.day+'</b><span>'+dateBR(l.date)+'</span><strong>'+Math.round(volumeForLog(l)).toLocaleString('pt-BR')+' kg</strong></div>').join('')||'<div class="empty">Nenhum registro.</div>')+'</section>'}
function dataPage(){return topNav()+'<section class="hero compact"><div class="eyebrow">Dados</div><h1>Conta e salvamento</h1><p>Seu treino fica salvo neste aparelho e, quando conectado, também na nuvem.</p></section><section class="card"><div class="account"><div><span>Conta</span><b>'+esc(user?.email||'Não conectado')+'</b></div><div class="cloudbox '+(cloudReady?'ok':'')+'">'+(cloudReady?'☁ Nuvem conectada':'📱 Salvamento local ativo')+'</div></div><div class="actions"><button class="secondary" onclick="exportData()">⬇️ Exportar registros</button><button class="secondary" onclick="importData()">⬆️ Importar registros</button><button class="danger" onclick="signOut()">Sair da conta</button></div></section>'}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='meu-treino-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importData(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{const f=input.files?.[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);if(!x.logs)throw Error();data=x;localSave();render();alert('Backup importado.')}catch(e){alert('Arquivo de backup inválido.')}};rd.readAsText(f)};input.click()}
function login(){return '<section class="card auth"><div class="authicon">🏋️</div><h1>Meu Treino</h1><p>Seu diário de musculação, cargas, repetições e progressão.</p><label>E-MAIL<input id="email" type="email" autocomplete="email" placeholder="seu@email.com"></label><label>SENHA<input id="password" type="password" autocomplete="current-password" placeholder="Sua senha"></label><button id="loginBtn" class="loginbtn" onclick="signIn()">ENTRAR</button><button class="secondary wide" onclick="signUp()">CRIAR CONTA</button><p class="loginhint">Os registros ficam salvos localmente e, quando a nuvem estiver disponível, também online.</p></section>'}
function render(){const app=$('app');if(!app)return;if(!user){app.innerHTML=login();return}let html=days.includes(current)?workout():current==='Histórico'?history():current==='Relatórios'?reports():dataPage();app.innerHTML=html+bottomNav()}
window.addEventListener('online',()=>{if(user)loadCloud()});window.addEventListener('offline',()=>setStatus('☁ Offline/local'));
init();
