(()=>{
'use strict';
const VERSION='20260901.save-v6';
const SUPABASE_URL='https://uvujytjdafcyacawcirp.supabase.co';
const SUPABASE_KEY='sb_publishable__mofqtls_ru76dDkIJbIew_G2f_wUKE';
const LOCAL_KEY='meu_treino_reset_v2';
const CLOUD_PREFIX='resetv1|';
const CDN='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.110.0/dist/umd/supabase.js';
let client=null,saving=false;
function toast(msg,ok=true){let e=document.getElementById('saveV6Toast');if(!e){e=document.createElement('div');e.id='saveV6Toast';Object.assign(e.style,{position:'fixed',left:'50%',bottom:'105px',zIndex:'999999',padding:'16px 22px',borderRadius:'16px',fontWeight:'800',fontSize:'18px',color:'#fff',boxShadow:'0 8px 30px rgba(0,0,0,.28)',maxWidth:'88vw',textAlign:'center',background:'#16803c'});document.body.appendChild(e)}e.textContent=msg;e.style.background=ok?'#16803c':'#b42318';e.style.opacity='1';clearTimeout(e.__t);e.__t=setTimeout(()=>e.style.opacity='0',4000)}
function status(t,on=false){const e=document.getElementById('cloudStatus');if(e){e.textContent=t;e.className='status '+(on?'on':'')}}
async function getClient(){if(client)return client;if(!window.supabase?.createClient){await new Promise((res,rej)=>{const s=document.createElement('script');s.src=CDN;s.crossOrigin='anonymous';s.onload=()=>window.supabase?.createClient?res():rej(new Error('Biblioteca Supabase não carregou.'));s.onerror=()=>rej(new Error('Não foi possível carregar o Supabase.'));document.head.appendChild(s)})}client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return client}
function parseKey(btn){const m=String(btn.getAttribute('onclick')||'').match(/commitSaved\(['"]([^'"]+)['"]\)/);return m?m[1]:null}
function buildPayload(key){const parts=String(key).split('|'),day=parts[0],date=parts[1];if(!day||!date)throw new Error('Não consegui identificar o dia do treino.');const rows={};document.querySelectorAll('.exercise').forEach((card,i)=>{const row={};card.querySelectorAll('.setrow').forEach((set,s)=>{const kg=set.querySelector('input[data-kind="kg"]')?.value??'';const reps=set.querySelector('input[data-kind="reps"]')?.value??'';if(kg!==''||reps!==''){row['kg'+s]=kg;row['reps'+s]=reps}});const obs=card.querySelector('textarea.obs')?.value??'';if(obs)row.observation=obs;rows[String(i)]=row});let total=0,valid=false;Object.values(rows).forEach(r=>{for(let s=0;s<20;s++){const kg=Number(r['kg'+s]),reps=Number(r['reps'+s]);if(kg>0&&reps>0){total+=kg*reps;valid=true}}});if(!valid)throw new Error('Preencha pelo menos uma série com carga e repetições antes de salvar.');const metricInputs=document.querySelectorAll('.metricsCard .metrics input');const duration=metricInputs[0]?.value||'';const avgBpm=metricInputs[1]?.value||'';const calories=metricInputs[2]?.value||'';const effort=document.querySelector('.metricsCard .metrics select')?.value||'';const notes=document.querySelector('.metricsCard textarea.notes')?.value||'';const csec=document.querySelector('.cardioCard');const ci=csec?csec.querySelectorAll('input'):[];const cardio={type:csec?.querySelector('select')?.value||'',duration:ci[0]?.value||'',distance:ci[1]?.value||'',calories:ci[2]?.value||'',avgBpm:ci[3]?.value||''};return {day,date,rows,notes,duration,avgBpm,calories,effort,cardio,completed:true,tonnageKg:total,tonnes:total/1000}}
function writeLocal(key,payload){let state;try{state=JSON.parse(localStorage.getItem(LOCAL_KEY)||'null')||{logs:{}}}catch(e){state={logs:{}}}state.logs=state.logs||{};state.logs[key]=payload;localStorage.setItem(LOCAL_KEY,JSON.stringify(state))}
async function cloudSave(key,payload){const c=await getClient();const {data:s,error:se}=await c.auth.getSession();if(se)throw se;const uid=s?.session?.user?.id;if(!uid)throw new Error('Sua sessão não está ativa. Entre novamente em Dados.');const logKey=CLOUD_PREFIX+key;const row={user_id:uid,log_key:logKey,day:payload.day,workout_date:payload.date,payload,updated_at:new Date().toISOString()};const {error}=await c.from('workout_logs').upsert(row,{onConflict:'user_id,log_key'});if(error)throw error;const v=await c.from('workout_logs').select('log_key,payload').eq('user_id',uid).eq('log_key',logKey).maybeSingle();if(v.error)throw v.error;if(!v.data?.payload)throw new Error('O Supabase não confirmou o treino.');return true}
async function save(btn){if(saving)return;saving=true;status('☁ Salvando...',true);btn.disabled=true;try{const key=parseKey(btn);if(!key)throw new Error('Não consegui identificar este treino.');const payload=buildPayload(key);writeLocal(key,payload);await cloudSave(key,payload);status('☁ Online • salvo',true);toast('✅ Treino salvo com sucesso!',true)}catch(e){console.error('[save-v6]',e);status('⚠ Não salvo na nuvem');toast('❌ Não foi possível salvar o treino.',false);alert('Não foi possível salvar o treino.\n\n'+(e?.message||String(e)))}finally{btn.disabled=false;saving=false}}
document.addEventListener('click',e=>{const btn=e.target?.closest?.('button');if(!btn||!/Salvar treino/i.test(btn.textContent||''))return;e.preventDefault();e.stopImmediatePropagation();save(btn)},true);
window.__saveV6={version:VERSION};
})();
