(()=>{ 
'use strict';
const VERSION='20260901.clean-save';
const SUPABASE_URL='https://uvujytjdafcyacawcirp.supabase.co';
const SUPABASE_KEY='sb_publishable__mofqtls_ru76dDkIJbIew_G2f_wUKE';
const LOCAL_KEY='meu_treino_reset_v2';
const CLOUD_PREFIX='resetv1|';
const CDN='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.110.0/dist/umd/supabase.js';
let client=null;
let saving=false;
function toast(message,ok=true){let el=document.getElementById('cleanSaveToast');if(!el){el=document.createElement('div');el.id='cleanSaveToast';Object.assign(el.style,{position:'fixed',left:'50%',bottom:'110px',zIndex:'999999',padding:'16px 22px',borderRadius:'15px',fontWeight:'800',fontSize:'17px',color:'#fff',boxShadow:'0 8px 30px rgba(0,0,0,.25)',maxWidth:'88vw',textAlign:'center',transition:'opacity .2s,transform .2s',opacity:'0',transform:'translate(-50%,15px)',pointerEvents:'none'});document.body.appendChild(el)}el.textContent=message;el.style.background=ok?'#16803c':'#b42318';el.style.opacity='1';el.style.transform='translate(-50%,0)';clearTimeout(el.__timer);el.__timer=setTimeout(()=>{el.style.opacity='0';el.style.transform='translate(-50%,15px)'},3500)}
function status(text,on=false){const e=document.getElementById('cloudStatus');if(e){e.textContent=text;e.className='status '+(on?'on':'')}}
async function getClient(){if(client)return client;if(!window.supabase?.createClient){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=CDN;s.crossOrigin='anonymous';s.onload=()=>window.supabase?.createClient?resolve():reject(new Error('Cliente Supabase não carregou.'));s.onerror=()=>reject(new Error('Não foi possível carregar o Supabase.'));document.head.appendChild(s)})}client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return client}
function readState(){try{return JSON.parse(localStorage.getItem(LOCAL_KEY)||'null')||{logs:{}}}catch(e){throw new Error('Não foi possível ler os dados locais do treino.')}}
function snapshotLogs(){const state=readState();return JSON.parse(JSON.stringify(state.logs||{}))}
function changedLog(before,after){const keys=new Set([...Object.keys(before||{}),...Object.keys(after||{})]);let found=null;for(const k of keys){const a=before?.[k],b=after?.[k];if(JSON.stringify(a)!==JSON.stringify(b)&&b){if(!found||String(b.date||'')>=String(found.payload.date||''))found={key:k,payload:b}}}return found}
function validWorkout(l){return !!(l?.date&&l?.completed!==false&&Object.values(l.rows||{}).some(r=>{for(let s=0;s<20;s++)if(Number(r?.['kg'+s])>0&&Number(r?.['reps'+s])>0)return true;return false}))}
async function uploadAndVerify(key,payload){const c=await getClient();const {data:sessionData,error:sessionError}=await c.auth.getSession();if(sessionError)throw sessionError;const uid=sessionData?.session?.user?.id;if(!uid)throw new Error('Sua sessão não está ativa. Entre novamente em Dados.');const row={user_id:uid,log_key:CLOUD_PREFIX+key,day:payload.day,workout_date:payload.date,payload:payload,updated_at:new Date().toISOString()};const {error}=await c.from('workout_logs').upsert(row,{onConflict:'user_id,log_key'});if(error)throw error;const verify=await c.from('workout_logs').select('log_key,workout_date,payload').eq('user_id',uid).eq('log_key',CLOUD_PREFIX+key).maybeSingle();if(verify.error)throw verify.error;if(!verify.data?.payload)throw new Error('O Supabase não confirmou o registro.');return verify.data}
async function saveClickedWorkout(before){if(saving)return;saving=true;status('☁ Salvando...',true);try{await new Promise(r=>setTimeout(r,650));const after=snapshotLogs();const change=changedLog(before,after);if(!change)throw new Error('O treino não foi registrado localmente. Preencha pelo menos uma série com carga e repetições e toque novamente em Salvar treino.');if(!validWorkout(change.payload))throw new Error('O treino não contém uma série válida com carga e repetições.');await uploadAndVerify(change.key,change.payload);status('☁ Online • treino salvo',true);toast('✅ Treino salvo com sucesso!',true)}catch(e){console.error('[clean-save]',e);status('⚠ Não salvo na nuvem');toast('❌ O treino NÃO foi salvo na nuvem.',false);alert('Não foi possível salvar o treino na nuvem.\n\n'+(e?.message||String(e)))}finally{saving=false}}
document.addEventListener('click',e=>{const btn=e.target?.closest?.('button');if(!btn||!/Salvar treino/i.test(btn.textContent||''))return;let before;try{before=snapshotLogs()}catch(err){before={}}setTimeout(()=>saveClickedWorkout(before),0)},{capture:true});
window.__cleanSave={version:VERSION,save:saveClickedWorkout};
})();
