(()=>{
'use strict';
const KEY='meu_treino_reset_v2';
const PLAN={
 Segunda:['Abdominal máquina','Pêndulo','Cadeira extensora','Stiff com barra ou halteres','Supino inclinado com halteres','Supino reto máquina','Crucifixo máquina'],
 Terça:['Barra fixa ou puxada neutra','Remada articulada com apoio no peito','Remada unilateral na polia','PULLDOWN','Rosca direta com barra W','Rosca inclinada com halteres','Rosca martelo com halteres'],
 Quarta:['Abdominal no Cross','Leg press 45°','Cadeira flexora bilateral','Mesa flexora','Desenvolvimento máquina','Elevação lateral na polia','Crucifixo inverso máquina','Panturrilha em pé ou no leg press'],
 Quinta:['Supino reto com barra','Supino inclinado máquina','Supino reto máquina','Crossover de baixo para cima','Tríceps francês unilateral na polia','Tríceps barra V','Tríceps testa com barra W'],
 Sexta:['Abdominal máquina','Agachamento Hack','Flexora unilateral','Remada baixa triângulo','Puxada alta pronada','Elevação lateral','Rosca Scott máquina','Tríceps corda'],
 Sábado:['Elevação lateral','Crucifixo inverso','Rosca martelo','Tríceps corda','Panturrilha sentado']
};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:0};
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{"logs":{}}')}catch(e){return{logs:{}}}}
function valid(l){return Object.values(l?.rows||{}).some(r=>{for(let s=0;s<20;s++)if(num(r?.['kg'+s])>0&&num(r?.['reps'+s])>0)return true;return false})}
function savedLogs(){const d=read();return Object.values(d.logs||{}).filter(l=>l&&l.completed!==false&&l.date&&valid(l));}
function dateObj(s){return new Date(s+'T12:00:00');}
function daysAgo(n){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-n);return d;}
function inRange(l,mode){const d=dateObj(l.date),now=new Date(),today=now.toISOString().slice(0,10);if(mode==='day')return l.date===today;if(mode==='month')return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();return d>=daysAgo(6);}
function setsFor(l,i){const r=l.rows?.[i]||{},out=[];for(let s=0;s<20;s++){const kg=num(r['kg'+s]),rep=num(r['reps'+s]);if(kg>0&&rep>0)out.push({kg,rep})}return out;}
function volume(l){let v=0;Object.keys(l.rows||{}).forEach(i=>setsFor(l,i).forEach(s=>v+=s.kg*s.rep));return v;}
function totalSets(l){let n=0;Object.keys(l.rows||{}).forEach(i=>n+=setsFor(l,i).length);return n;}
function records(){const logs=savedLogs().sort((a,b)=>String(b.date).localeCompare(String(a.date)));const map={};logs.forEach(l=>{(PLAN[l.day]||[]).forEach((name,i)=>{const sets=setsFor(l,i);if(sets.length)(map[name]??=[]).push({date:l.date,day:l.day,sets});});});return map;}
function best(a){return a.reduce((x,s)=>!x||s.kg>x.kg||(s.kg===x.kg&&s.rep>x.rep)?s:x,null);}
function advice(name,arr){arr=[...arr].sort((a,b)=>String(b.date).localeCompare(String(a.date)));const cur=arr[0],prev=arr[1],cb=best(cur.sets),pb=prev&&best(prev.sets);if(!pb)return ['🎯','MANTER CARGA',`Primeiro registro comparável: ${cb.kg} kg × ${cb.rep} reps. Confirme execução antes de subir.`];if(cb.kg>pb.kg)return ['📈','AUMENTAR CARGA',`Você saiu de ${pb.kg} para ${cb.kg} kg. Consolide a nova carga.`];if(cb.kg===pb.kg&&cb.rep>pb.rep)return ['🚀','AUMENTAR CARGA',`Manteve ${cb.kg} kg e aumentou repetições. Ao atingir o topo da faixa, suba a carga.`];if(cb.kg===pb.kg&&cb.rep===pb.rep)return ['🔁','AUMENTAR REP',`Repita ${cb.kg} kg e tente ganhar 1–2 repetições na próxima sessão.`];return ['🎯','MANTER CARGA',`Mantenha ${cb.kg} kg e priorize execução; houve queda de desempenho.`];}
function selectedMode(){return window.__reportMode||'week';}
function analysis(mode){const all=savedLogs(),logs=all.filter(l=>inRange(l,mode));const vol=logs.reduce((a,l)=>a+volume(l),0),sets=logs.reduce((a,l)=>a+totalSets(l),0);let text;if(!logs.length)text='Ainda não há treino salvo neste período para avaliar.';else if(logs.length===1)text=`Treino registrado com ${sets} séries e ${Math.round(vol).toLocaleString('pt-BR')} kg de peso levantado. Compare a próxima sessão para decidir a progressão.`;else{text=`Foram ${logs.length} treinos, ${sets} séries e ${Math.round(vol).toLocaleString('pt-BR')} kg levantados. Média: ${Math.round(vol/logs.length).toLocaleString('pt-BR')} kg por treino.`;}return{text,logs};}
let lastSignature='';
function render(){const card=document.querySelector('.coachReportCard');if(!card)return;const mode=selectedMode(),a=analysis(mode),map=records();const entries=Object.entries(map).filter(([,arr])=>arr.some(x=>inRange({date:x.date},mode))).sort((x,y)=>x[0].localeCompare(y[0])).slice(0,12);const signature=JSON.stringify([mode,a.logs.map(x=>x.date),Object.entries(map).map(([n,v])=>[n,v.map(x=>[x.date,x.sets])])]);if(signature===lastSignature&&card.querySelector('#coachLive'))return;lastSignature=signature;let box=card.querySelector('#coachLive');if(!box){box=document.createElement('div');box.id='coachLive';card.appendChild(box);}box.innerHTML=`<div class="coachLiveHead"><div><b>🤖 COACH IA</b><small>Análise automática dos registros salvos</small></div><button type="button" id="coachAnalyzeNow">ANALISAR AGORA</button></div><div class="coachLiveSummary">${esc(a.text)}</div><div class="coachLiveGrid">${entries.map(([name,arr])=>{const x=advice(name,arr);return `<div class="coachLiveItem"><b>${esc(name)}</b><strong>${x[0]} ${x[1]}</strong><small>${esc(x[2])}</small></div>`}).join('')||'<div class="coachLiveEmpty">Salve um treino completo para o Coach IA comparar carga e repetições.</div>'}</div>`;const btn=box.querySelector('#coachAnalyzeNow');if(btn)btn.onclick=()=>{btn.disabled=true;btn.textContent='ANALISANDO...';lastSignature='';window.setTimeout(()=>render(),120);};}
function cloudHint(){const st=document.getElementById('cloudStatus');if(!st)return;const txt=st.textContent||'';let b=document.getElementById('cloudHint');const offline=txt.includes('Salvo neste aparelho')||txt.includes('Offline/local')||txt.includes('Pronto para entrar');if(offline){if(!b){b=document.createElement('div');b.id='cloudHint';b.innerHTML='<b>⚠ Nuvem desconectada</b><span>Os registros estão sendo salvos apenas neste aparelho. Entre em <b>Dados</b> para reconectar ao Supabase.</span><button type="button">ABRIR DADOS</button>';document.body.appendChild(b);const bt=b.querySelector('button');if(bt)bt.onclick=()=>{if(typeof window.go==='function')window.go('Dados')};}}else if(b)b.remove();}
const style=document.createElement('style');style.textContent='#coachLive{margin-top:16px;padding:16px;border:1px solid #ffd8b5;border-radius:16px;background:#fff9f3}.coachLiveHead{display:flex;justify-content:space-between;gap:12px;align-items:center}.coachLiveHead b{display:block;font-size:13px;color:#b64d00}.coachLiveHead small{display:block;color:#718096;margin-top:3px}.coachLiveHead button{border:0;border-radius:10px;padding:10px 14px;background:#f36b00;color:#fff;font-weight:800;cursor:pointer}.coachLiveHead button:disabled{opacity:.65}.coachLiveSummary{margin-top:12px;font-weight:700;line-height:1.45}.coachLiveGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:12px}.coachLiveItem,.coachLiveEmpty{border:1px solid #eadfd5;border-radius:12px;background:#fff;padding:11px}.coachLiveItem b,.coachLiveItem strong,.coachLiveItem small{display:block}.coachLiveItem strong{font-size:12px;margin-top:5px}.coachLiveItem small{color:#718096;margin-top:4px;line-height:1.35}.coachLiveEmpty{color:#718096}.coachLiveItem strong{color:#b64d00}#cloudHint{position:fixed;right:18px;bottom:18px;z-index:9999;max-width:360px;padding:14px 16px;border-radius:14px;background:#fff7ed;border:1px solid #fdba74;box-shadow:0 8px 30px #0002;display:grid;grid-template-columns:1fr auto;gap:4px 12px;font-size:12px}#cloudHint b{color:#b45309}#cloudHint span{grid-column:1/-1;color:#667085;line-height:1.35}#cloudHint button{grid-column:2;grid-row:1;border:0;background:#f36b00;color:white;border-radius:9px;padding:8px 10px;font-weight:800}@media(max-width:700px){.coachLiveGrid{grid-template-columns:1fr}#cloudHint{left:12px;right:12px;bottom:12px}}';document.head.appendChild(style);
let observerTimer=0,observing=false;
const obs=new MutationObserver(()=>{if(observerTimer)return;observerTimer=window.setTimeout(()=>{observerTimer=0;if(document.querySelector('.coachReportCard'))render();cloudHint();},80);});
obs.observe(document.documentElement,{childList:true,subtree:true});
window.addEventListener('load',()=>window.setTimeout(()=>{render();cloudHint();},300));
})();
