(function(){
'use strict';
const KEY='meu_treino_reset_v1';
const EX={Segunda:['Abdominal máquina','Pêndulo','Cadeira extensora','Stiff com barra ou halteres','Supino inclinado com halteres','Supino reto máquina','Crucifixo máquina'],Terça:['Barra fixa ou puxada neutra','Remada articulada com apoio no peito','Remada unilateral na polia','PULLDOWN','Rosca direta com barra W','Rosca inclinada com halteres','Rosca martelo com halteres'],Quarta:['Abdominal no Cross','Leg press 45°','Cadeira flexora bilateral','Mesa flexora','Desenvolvimento máquina','Elevação lateral na polia','Crucifixo inverso máquina','Panturrilha em pé ou no leg press'],Quinta:['Supino reto com barra','Supino inclinado máquina','Supino reto máquina','Crossover de baixo para cima','Tríceps francês unilateral na polia','Tríceps barra V','Tríceps testa com barra W'],Sexta:['Abdominal máquina','Agachamento Hack','Flexora unilateral','Remada baixa triângulo','Puxada alta pronada','Elevação lateral','Rosca Scott máquina','Tríceps corda'],Sábado:['Elevação lateral','Crucifixo inverso','Rosca martelo','Tríceps corda','Panturrilha sentado']};
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{"logs":{}}')}catch(e){return{logs:{}}}}
function n(v){const x=Number(v);return Number.isFinite(x)?x:0}
function advice(){const map={};Object.values(read().logs||{}).forEach(l=>{if(!l||l.draft||!l.date||l.appleFitness?.imported)return;const ex=EX[String(l.day||'').split(' — ')[0]]||[];ex.forEach((name,i)=>{const r=l.rows?.[i]||{},sets=[];for(let s=0;s<15;s++){const kg=n(r['kg'+s]),rep=n(r['reps'+s]);if(kg>0&&rep>0)sets.push({kg,rep})}if(sets.length)(map[name]??=[]).push({date:l.date,sets})})});const out=[];Object.entries(map).forEach(([name,arr])=>{arr.sort((a,b)=>String(b.date).localeCompare(String(a.date)));const cur=arr[0],prev=arr[1];const best=x=>x.sets.reduce((a,b)=>b.kg>a.kg?b:a,x.sets[0]);const cb=best(cur),pb=prev&&best(prev);if(pb&&cb.kg>pb.kg)out.push(['📈',name,`Subiu de ${pb.kg} para ${cb.kg} kg.`]);else if(pb&&cb.kg===pb.kg&&cb.rep>pb.rep)out.push(['📈',name,`Manteve ${cb.kg} kg e fez mais repetições.`]);else if(cb.rep>=10)out.push(['🚀',name,`Boa margem: ${cb.kg} kg × ${cb.rep} reps.`]);else out.push(['🎯',name,`Mantenha ${cb.kg} kg e busque mais 1–2 reps.`])});return out.slice(0,5)}
function inject(){const panel=document.getElementById('progressDashboard');if(!panel||document.getElementById('coachSection'))return;const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const a=advice();const box=document.createElement('div');box.id='coachSection';box.className='coach-section';box.innerHTML=`<h3>🧠 Coach de progressão</h3><p>Leitura dos seus últimos registros para orientar a próxima sessão.</p>${a.length?`<div class="coach-list">${a.map(x=>`<div><span>${x[0]}</span><section><b>${esc(x[1])}</b><small>${esc(x[2])}</small></section></div>`).join('')}</div>`:'<div class="coach-empty">Salve mais treinos para o coach começar a comparar sua evolução.</div>'}<small class="coach-note">Sugestões baseadas no histórico registrado. Priorize técnica e execução antes de aumentar a carga.</small>`;panel.appendChild(box)}
const style=document.createElement('style');style.textContent='.coach-section{border-top:1px solid #e3e8ed;margin-top:18px;padding-top:16px}.coach-section h3{margin:0 0 4px}.coach-section>p{margin:0;color:#718096}.coach-list{display:grid;gap:8px;margin-top:12px}.coach-list>div{display:flex;gap:10px;align-items:center;border:1px solid #e1e7ec;border-radius:13px;padding:11px 12px}.coach-list span{font-size:21px}.coach-list b,.coach-list small{display:block}.coach-list small{color:#718096;margin-top:2px}.coach-empty{margin-top:10px;padding:14px;border-radius:13px;background:#f4f6f8;color:#718096}.coach-note{display:block;color:#8994a3;font-size:11px;margin-top:12px}';document.head.appendChild(style);
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(/Relatórios/.test(b.textContent||''))setTimeout(inject,350)},true);
})();