const URL_SB='https://uvujytjdafcyacawcirp.supabase.co',KEY_SB='sb_publishable__mofqtls_ru76dDkIJbIew_G2f_wUKE',STORE='meu_treino_pro_v2';
const W={Segunda:{i:'🟢',t:'Pernas + Peito',e:[['Abdominal máquina',3,'12–15'],['Pêndulo',4,'6–10'],['Cadeira extensora',3,'10–15'],['Stiff com barra ou halteres',3,'8–10'],['Supino inclinado com halteres',4,'8–10'],['Supino reto máquina',3,'8–12'],['Crucifixo máquina',2,'12–15']]},Terça:{i:'🔵',t:'Costas + Bíceps',e:[['Barra fixa ou puxada neutra',4,'6–10'],['Remada articulada com apoio no peito',4,'8–12'],['Remada unilateral na polia',3,'10–12'],['PULLDOWN',3,'10–15'],['Rosca direta com barra W',3,'8–12'],['Rosca inclinada com halteres',3,'10–12'],['Rosca martelo com halteres',2,'10–12']]},Quarta:{i:'🟠',t:'Pernas + Ombros',e:[['Abdominal máquina',3,'12–15'],['Leg press 45°',4,'8–12'],['Elevação pélvica',3,'8–12'],['Cadeira flexora bilateral',4,'8–12'],['Mesa flexora',3,'10–15'],['Desenvolvimento máquina',3,'8–10'],['Elevação lateral na polia',4,'10–15'],['Crucifixo inverso máquina',3,'12–15'],['Panturrilha em pé ou no leg press',4,'10–15']]},Quinta:{i:'🔴',t:'Peito + Tríceps',e:[['Supino reto com barra',4,'6–10'],['Supino inclinado máquina',3,'8–12'],['Supino reto máquina',3,'8–12'],['Crossover de baixo para cima',2,'12–15'],['Tríceps francês unilateral na polia',3,'10–12'],['Tríceps barra V',3,'8–12'],['Tríceps testa com barra W',2,'10–12']]},Sexta:{i:'🟣',t:'Full Body + Pontos fracos',e:[['Abdominal máquina',3,'12–15'],['Hack squat',3,'8–12'],['Flexora unilateral',3,'10–12'],['Remada baixa triângulo',3,'8–12'],['Puxada alta pronada',3,'8–12'],['Supino inclinado com halteres',3,'8–12'],['Elevação lateral',3,'12–15'],['Rosca Scott máquina',2,'10–12'],['Tríceps corda',2,'10–15'],['Panturrilha',4,'12–15']]}};
const SAT=[['Elevação lateral',3,'12–15'],['Crucifixo inverso',3,'12–15'],['Rosca martelo',3,'10–12'],['Tríceps corda',3,'10–12'],['Panturrilha',4,'12–15']];
let D=(()=>{try{return JSON.parse(localStorage.getItem(STORE))||{logs:{}}}catch(e){return{logs:{}}}})(),day='Segunda',usr=null,sb=null,online=false,timer=null,hist='Pêndulo';
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const date=()=>new Date().toISOString().slice(0,10),k=()=>day+'|'+date(),fmt=x=>new Date(x+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'});
function save(){try{localStorage.setItem(STORE,JSON.stringify(D))}catch(e){}}function st(x,on){const e=document.getElementById('cloudStatus');if(e){e.textContent=x;e.className='status '+(on?'on':'')}}
function log(){return D.logs[k()]||(D.logs[k()]={day,date:date(),rows:{},notes:''})}
async function syncOne(id){if(!usr||!online||!sb||!D.logs[id])return;const l=D.logs[id],r=await sb.from('workout_logs').upsert({user_id:usr.id,log_key:id,day:l.day,workout_date:l.date,payload:l,updated_at:new Date().toISOString()},{onConflict:'user_id,log_key'});if(r.error){console.error(r.error);st('⚠ Erro ao salvar',false)}else st('☁ Online • salvo',true)}
function queue(id){clearTimeout(timer);timer=setTimeout(()=>syncOne(id),500)}
async function loadCloud(){if(!usr||!sb)return;const r=await sb.from('workout_logs').select('log_key,payload').order('workout_date',{ascending:false});if(r.error){st('⚠ Nuvem indisponível',false);return}online=true;const local={...D.logs};if(!r.data.length){for(const id of Object.keys(local))await syncOne(id)}else{for(const x of r.data)if(x.payload)D.logs[x.log_key]=x.payload;for(const id of Object.keys(local))if(!r.data.some(x=>x.log_key===id))await syncOne(id)}save();st('☁ Online • salvo',true);render()}
async function login(){const e=document.getElementById('email').value.trim(),p=document.getElementById('password').value;if(!sb)return alert('A conexão ainda não carregou. Recarregue a página.');const r=await sb.auth.signInWithPassword({email:e,password:p});if(r.error)return alert(r.error.message);usr=r.data.user;st('☁ Conectando…',true);await loadCloud()}
async function signup(){const e=document.getElementById('email').value.trim(),p=document.getElementById('password').value;if(!e||p.length<6)return alert('Use e-mail e senha com pelo menos 6 caracteres.');const r=await sb.auth.signUp({email:e,password:p});alert(r.error?r.error.message:'Conta criada. Confirme o e-mail se for solicitado e entre.')}
async function logout(){if(sb)await sb.auth.signOut();usr=null;online=false;st('☁ Offline/local',false);render()}
function auth(){app.innerHTML='<div class="card auth"><div style="font-size:42px">🏋️</div><h1>Meu Treino</h1><p>Diário de musculação com histórico de cargas e progressão.</p><input id="email" type="email" placeholder="Seu e-mail"><input id="password" type="password" placeholder="Senha (mínimo 6 caracteres)"><button class="loginbtn" onclick="login()">ENTRAR</button><button class="secondary" style="width:100%;margin-top:7px" onclick="signup()">CRIAR CONTA</button></div>'}
function topNav(){return '<div class="nav"><button class="active">🏋️ Treino</button><button onclick="go(\'Histórico\')">📈 Histórico</button><button onclick="go(\'Relatórios\')">📊 Relatório</button><button onclick="go(\'Dados\')">⚙️ Dados</button></div>'}
function days(){return '<div class="daystrip">'+Object.keys(W).map(x=>'<button class="'+(day===x?'active':'')+'" onclick="go(\''+x+'\')">'+W[x].i+'<small>'+x.slice(0,3).toUpperCase()+'</small></button>').join('')+'<button class="'+(day==='Sábado'?'active':'')+'" onclick="go(\'Sábado\')">🟣<small>SÁB</small></button></div>'}
function setv(i,s,f,v){const l=log();l.rows[i]??={};l.rows[i][f+s]=v;save();queue(k());suggest(i)}
function obs(i,v){const l=log();l.rows[i]??={};l.rows[i].observation=v;save();queue(k())}
function metric(f,v){log()[f]=v;save();queue(k());render()}
function prev(name){const arr=Object.values(D.logs).filter(x=>x.day===day&&x.date<date()).sort((a,b)=>b.date.localeCompare(a.date));for(const l of arr){const ex=(W[day]?.e||SAT).findIndex(x=>x[0]===name);if(ex>=0&&l.rows?.[ex])return l.rows[ex]}}
function suggest(i){const el=document.getElementById('sg'+i);if(!el)return;const ex=(W[day]?.e||SAT)[i],r=log().rows[i]||{},vals=Array.from({length:ex[1]},(_,s)=>+r['reps'+s]).filter(Boolean);if(!vals.length){el.innerHTML='';return}const m=ex[2].match(/(\d+)[–-](\d+)/),hi=m?+m[2]:999,avg=vals.reduce((a,b)=>a+b,0)/vals.length;el.innerHTML=vals.length===ex[1]&&avg>=hi?'<span class="up">⬆ PROGRESSÃO: pode subir a carga</span>':'<span class="keep">→ Dentro da faixa: mantenha a carga</span>'}
function exCard(ex,i){const r=log().rows[i]||{};let rows='';for(let s=0;s<ex[1];s++)rows+='<div class="setrow"><div class="setno">'+(s+1)+'</div><input class="field" type="number" step="0.5" placeholder="kg" value="'+esc(r['kg'+s]??'')+'" onchange="setv('+i+','+s+',\'kg\',this.value)"><input class="field" type="number" placeholder="reps" value="'+esc(r['reps'+s]??'')+'" onchange="setv('+i+','+s+',\'reps\',this.value)"></div>';return '<article class="exercise"><div class="exhead"><div><div class="exname">'+(i+1)+'. '+esc(ex[0])+'</div><div class="meta">'+ex[1]+' séries • '+ex[2]+' reps</div></div><div class="tag">'+ex[2]+'</div></div><div class="sets"><div class="sethead"><span>SÉRIE</span><span>CARGA KG</span><span>REPS</span></div>'+rows+'</div><textarea class="obs" rows="2" placeholder="Técnica, falha, dor, execução..." onchange="obs('+i+',this.value)">'+esc(r.observation||'')+'</textarea><div id="sg'+i+'" class="suggest"></div></article>'}
function workout(){const ex=day==='Sábado'?SAT:W[day].e,l=log();app.innerHTML=topNav()+'<section class="hero"><div class="eyebrow">Treino de hoje</div><h1>'+((W[day]?.i)||'🟣')+' '+(W[day]?.t||'Treino opcional')+'</h1><p>'+fmt(date())+' • registre cada série e acompanhe sua progressão.</p></section>'+days()+'<div class="stats"><div class="stat"><span>Exercícios</span><b>'+ex.length+'</b></div><div class="stat"><span>Séries</span><b>'+ex.reduce((a,e)=>a+e[1],0)+'</b></div><div class="stat"><span>Tempo</span><b>'+esc(l.duration||'—')+'</b></div><div class="stat"><span>RPE</span><b>'+esc(l.effort||'—')+'</b></div></div><div class="exercise-grid">'+ex.map(exCard).join('')+'</div><section class="card"><div class="sectiontitle"><h3>📊 Dados do treino</h3></div><div class="metrics"><div><label>TEMPO</label><input value="'+esc(l.duration||'')+'" placeholder="1h 05min" onchange="metric(\'duration\',this.value)"></div><div><label>BPM MÉDIO</label><input type="number" value="'+esc(l.avgBpm||'')+'" placeholder="119" onchange="metric(\'avgBpm\',this.value)"></div><div><label>CALORIAS</label><input type="number" value="'+esc(l.calories||'')+'" placeholder="507" onchange="metric(\'calories\',this.value)"></div><div><label>ESFORÇO</label><select onchange="metric(\'effort\',this.value)"><option value="">RPE</option>'+Array.from({length:10},(_,i)=>'<option '+(String(l.effort)===String(i+1)?'selected':'')+'>'+(i+1)+'/10</option>').join('')+'</select></div></div><h3 style="font-size:13px;margin:16px 0 7px">📝 Observações gerais</h3><textarea class="notes" onchange="log().notes=this.value;save();queue(k())" placeholder="Energia, pump, dores, desempenho...">'+esc(l.notes||'')+'</textarea><div class="actions"><button class="primary" onclick="window.print()">🖨️ Relatório</button><button class="danger" onclick="clearDay()">Limpar dia</button></div></section>';ex.forEach((_,i)=>suggest(i))}
function history(){const names=new Set();Object.values(W).forEach(w=>w.e.forEach(e=>names.add(e[0])));SAT.forEach(e=>names.add(e[0]));const opt=[...names].sort().map(n=>'<option '+(n===hist?'selected':'')+'>'+esc(n)+'</option>').join(''),out=[];Object.values(D.logs).forEach(l=>(W[l.day]?.e||SAT).forEach((e,i)=>{if(e[0]!==hist||!l.rows?.[i])return;const r=l.rows[i],s=[];for(let j=0;j<e[1];j++)if(r['kg'+j]!==undefined||r['reps'+j]!==undefined)s.push('S'+(j+1)+': '+(r['kg'+j]||'—')+' kg × '+(r['reps'+j]||'—'));if(s.length)out.push({d:l.date,day:l.day,s})}));out.sort((a,b)=>b.d.localeCompare(a.d));app.innerHTML=topNav()+'<section class="hero"><div class="eyebrow">Progressão</div><h1>📈 Histórico de cargas</h1><p>Compare seus treinos anteriores e veja sua evolução.</p></section><div class="card"><select class="select" onchange="hist=this.value;history()">'+opt+'</select></div><div class="card"><div class="sectiontitle"><h3>'+esc(hist)+'</h3><span class="tag">'+out.length+' REGISTROS</span></div>'+(out.length?out.map(x=>'<div class="historyrow"><b>'+fmt(x.d)+' — '+x.day+'</b><div class="chips">'+x.s.map(s=>'<span class="chip">'+esc(s)+'</span>').join('')+'</div></div>').join(''):'<div class="empty">Ainda não há registros.</div>')+'</div>'}
function report(){const a=Object.values(D.logs);let sets=0,reps=0,vol=0;a.forEach(l=>Object.values(l.rows||{}).forEach(r=>{for(const x in r)if(x.startsWith('reps')&&r[x]!==''){const q=+r[x]||0;sets++;reps+=q;vol+=(+r[x.replace('reps','kg')]||0)*q}}));app.innerHTML=topNav()+'<section class="hero"><div class="eyebrow">Performance</div><h1>📊 Relatório</h1><p>Resumo do seu histórico de musculação.</p></section><div class="stats"><div class="stat"><span>Sessões</span><b>'+a.length+'</b></div><div class="stat"><span>Séries</span><b>'+sets+'</b></div><div class="stat"><span>Reps</span><b>'+reps+'</b></div><div class="stat"><span>Volume</span><b>'+Math.round(vol).toLocaleString('pt-BR')+' kg</b></div></div><div class="card">'+(a.length?a.sort((x,y)=>y.date.localeCompare(x.date)).map(l=>'<div class="historyrow"><b>'+fmt(l.date)+' — '+l.day+'</b><div class="meta">'+(l.duration||'Tempo —')+' • '+(l.avgBpm||'BPM —')+' • '+(l.calories||'kcal —')+' • '+(l.effort?l.effort+'/10':'RPE —')+'</div></div>').join(''):'<div class="empty">Nenhum treino registrado.</div>')+'</div>'}
function dataPage(){app.innerHTML=topNav()+'<section class="hero"><div class="eyebrow">Conta</div><h1>⚙️ Dados</h1><p>Treinos sincronizados na nuvem e mantidos como cópia local.</p></section><div class="card"><b>'+esc(usr?.email||'não conectado')+'</b><div class="actions"><button class="primary" onclick="backup()">⬇ Backup</button><button class="secondary" onclick="document.getElementById(\'imp\').click()">⬆ Importar</button><input id="imp" type="file" accept=".json" hidden onchange="importBackup(this)"><button class="danger" onclick="logout()">Sair</button></div></div>'}
function backup(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(D,null,2)],{type:'application/json'}));a.download='backup-meu-treino-'+date()+'.json';a.click()}
function importBackup(i){const f=i.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{D=JSON.parse(r.result);save();if(usr&&online)for(const id of Object.keys(D.logs))await syncOne(id);render();alert('Backup importado.')}catch(e){alert('Backup inválido.')}};r.readAsText(f)}
async function clearDay(){if(!confirm('Apagar o treino de hoje?'))return;const id=k();delete D.logs[id];save();if(usr&&online)await sb.from('workout_logs').delete().eq('user_id',usr.id).eq('log_key',id);render()}
function bottom(){const n=document.getElementById('footnav');n.innerHTML='<button class="'+(['Segunda','Terça','Quarta','Quinta','Sexta','Sábado'].includes(day)?'active':'')+'" onclick="go(\'Segunda\')">🏋️<br>Treino</button><button class="'+(day==='Histórico'?'active':'')+'" onclick="go(\'Histórico\')">📈<br>Histórico</button><button class="'+(day==='Relatórios'?'active':'')+'" onclick="go(\'Relatórios\')">📊<br>Relatório</button><button class="'+(day==='Dados'?'active':'')+'" onclick="go(\'Dados\')">⚙️<br>Dados</button>'}
function render(){if(!usr){auth();bottom();return}if(day==='Histórico')history();else if(day==='Relatórios')report();else if(day==='Dados')dataPage();else workout();bottom()}
function go(x){day=x;render()}
(async function(){try{sb=window.supabase.createClient(URL_SB,KEY_SB);const s=await sb.auth.getSession();usr=s.data.session?.user||null;if(usr)await loadCloud();else render();sb.auth.onAuthStateChange((_e,s)=>{usr=s?.user||null;if(usr&&!online)loadCloud();else if(!usr){online=false;render()}})}catch(e){console.error(e);render()}})();