/* Meu Treino — PDFs dentro de Relatórios */
(function(){
'use strict';
const getPdf=()=>window.jspdf&&window.jspdf.jsPDF?window.jspdf.jsPDF:null;
const isoToday=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const fmtDate=d=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'});
const mondayOf=date=>{const d=new Date(date+'T12:00:00'),n=d.getDay()||7;d.setDate(d.getDate()-n+1);return d.toISOString().slice(0,10)};
const addDays=(date,n)=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const logsForDate=date=>Object.values(data?.logs||{}).filter(l=>l.date===date);
const volume=l=>{let total=0;Object.values(l?.rows||{}).forEach(r=>{for(let s=0;s<10;s++){const kg=Number(r?.['kg'+s]),rp=Number(r?.['reps'+s]);if(kg>0&&rp>0)total+=kg*rp}});return total};
const setCount=l=>{let total=0;Object.values(l?.rows||{}).forEach(r=>{for(let s=0;s<10;s++)if(Number(r?.['kg'+s])>0&&Number(r?.['reps'+s])>0)total++});return total};
const ensureSpace=(doc,y,n)=>y+n>282?(doc.addPage(),18):y;
const text=(doc,v,x,y,w,size=9)=>{doc.setFontSize(size);const lines=doc.splitTextToSize(String(v||''),w||175);doc.text(lines,x,y);return y+lines.length*5};
function header(doc,title,subtitle){doc.setFillColor(242,111,0);doc.roundedRect(12,10,186,22,4,4,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(17);doc.text('MEU TREINO',20,23);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text('MUSCULACAO • PROGRESSAO',112,23);doc.setTextColor(25,35,48);doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text(title,14,43);doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text(subtitle,14,50);return 60}
function daily(date){const JsPDF=getPdf();if(!JsPDF){alert('O gerador de PDF ainda está carregando.');return}const logs=logsForDate(date),doc=new JsPDF({unit:'mm',format:'a4'});let y=header(doc,'Relatorio diario',fmtDate(date));if(!logs.length){doc.text('Nenhum treino registrado nesta data.',14,y);doc.save('meu-treino-diario-'+date+'.pdf');return}logs.forEach(l=>{y=ensureSpace(doc,y,35);doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text((l.day||'Treino')+' — '+(workouts[l.day]?.title||'Treino opcional'),14,y);y+=7;doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text('Tempo: '+(l.duration||'—')+' | BPM medio: '+(l.avgBpm||'—')+' | Calorias: '+(l.calories||'—')+' | RPE: '+(l.effort||'—')+' | Volume: '+Math.round(volume(l)).toLocaleString('pt-BR')+' kg',14,y);y+=7;(exFor(l.day)||[]).forEach((e,i)=>{const r=l.rows?.[i]||{};y=ensureSpace(doc,y,22);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text((i+1)+'. '+e[0]+' ('+e[2]+' reps)',16,y);y+=5;let any=false;for(let s=0;s<e[1];s++){const kg=r['kg'+s],rp=r['reps'+s];if((kg!==undefined&&kg!=='')||(rp!==undefined&&rp!=='')){y=ensureSpace(doc,y,6);doc.setFont('helvetica','normal');doc.text('Serie '+(s+1)+': '+(kg||'—')+' kg x '+(rp||'—')+' reps',20,y);y+=4.5;any=true}}if(r.observation)y=text(doc,'Observacao: '+r.observation,20,ensureSpace(doc,y,10),170,8);if(!any){doc.setFontSize(8);doc.text('Sem carga/repeticoes registradas.',20,y);y+=4.5}});if(l.notes){y=ensureSpace(doc,y,15);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('Observacoes gerais',16,y);y+=5;doc.setFont('helvetica','normal');y=text(doc,l.notes,16,y,175,9)}y+=5});doc.save('meu-treino-diario-'+date+'.pdf')}
function weekly(date){const JsPDF=getPdf();if(!JsPDF){alert('O gerador de PDF ainda está carregando.');return}const start=mondayOf(date),end=addDays(start,6),week=Array.from({length:7},(_,i)=>{const d=addDays(start,i);return{date:d,logs:logsForDate(d)}}),active=week.filter(x=>x.logs.length),totalVolume=active.reduce((a,x)=>a+x.logs.reduce((b,l)=>b+volume(l),0),0),totalKcal=active.reduce((a,x)=>a+x.logs.reduce((b,l)=>b+Number(l.calories||0),0),0),totalSets=active.reduce((a,x)=>a+x.logs.reduce((b,l)=>b+setCount(l),0),0),bpms=active.flatMap(x=>x.logs.map(l=>Number(l.avgBpm)).filter(Boolean)),avg=bpms.length?Math.round(bpms.reduce((a,b)=>a+b,0)/bpms.length):'—';const doc=new JsPDF({unit:'mm',format:'a4'});let y=header(doc,'Relatorio semanal',fmtDate(start)+' a '+fmtDate(end));doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('Resumo da semana',14,y);y+=7;doc.setFont('helvetica','normal');y=text(doc,'Treinos realizados: '+active.reduce((a,x)=>a+x.logs.length,0),16,y,175,10);y=text(doc,'Series registradas: '+totalSets,16,y,175,10);y=text(doc,'Volume total: '+Math.round(totalVolume).toLocaleString('pt-BR')+' kg',16,y,175,10);y=text(doc,'Calorias registradas: '+Math.round(totalKcal).toLocaleString('pt-BR')+' kcal',16,y,175,10);y=text(doc,'BPM medio dos treinos com registro: '+avg,16,y,175,10);y+=4;week.forEach(day=>{y=ensureSpace(doc,y,25);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text(fmtDate(day.date),14,y);y+=6;if(!day.logs.length){doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text('Sem treino registrado.',18,y);y+=7;return}day.logs.forEach(log=>{y=ensureSpace(doc,y,18);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text((log.day||'Treino')+' — '+(workouts[log.day]?.title||'Treino opcional'),18,y);y+=5;doc.setFont('helvetica','normal');doc.setFontSize(8.5);doc.text('Volume '+Math.round(volume(log)).toLocaleString('pt-BR')+' kg | '+setCount(log)+' series | '+(log.calories||'—')+' kcal | '+(log.avgBpm||'—')+' bpm | '+(log.duration||'—')+' | RPE '+(log.effort||'—'),18,y);y+=6;(exFor(log.day)||[]).forEach((e,i)=>{const r=log.rows?.[i]||{},entries=[];for(let s=0;s<e[1];s++){const kg=r['kg'+s],rp=r['reps'+s];if((kg!==undefined&&kg!=='')||(rp!==undefined&&rp!==''))entries.push((kg||'—')+' kg x '+(rp||'—'))}if(entries.length)y=text(doc,(i+1)+'. '+e[0]+': '+entries.join(' | '),22,ensureSpace(doc,y,8),165,8)})}) ;y+=3});doc.save('meu-treino-semanal-'+start+'-'+end+'.pdf')}
function isReports(){const app=document.getElementById('app');if(!app)return false;return [...app.querySelectorAll('.nav button,.bottomnav button')].some(b=>b.classList.contains('active')&&/Relatórios/i.test(b.textContent||''))}
function install(){const app=document.getElementById('app');if(!app)return;const reports=isReports();const old=document.getElementById('pdfTools');if(old&&!reports)old.remove();if(!reports||old)return;const anchor=[...app.querySelectorAll('.hero.compact')].find(x=>/Progressão/i.test(x.textContent||''));if(!anchor)return;const box=document.createElement('section');box.id='pdfTools';box.className='card';box.innerHTML='<h2>📄 Relatórios em PDF</h2><p class="muted">Gere o relatório diário ou semanal diretamente pela aba Relatórios.</p><div class="pdfrow"><label>DATA<input id="pdfDate" type="date" value="'+isoToday()+'"></label><button class="primary" id="pdfDayBtn">PDF DIÁRIO</button><button class="secondary" id="pdfWeekBtn">PDF SEMANAL</button></div>';anchor.after(box);document.getElementById('pdfDayBtn').onclick=()=>daily(document.getElementById('pdfDate').value||isoToday());document.getElementById('pdfWeekBtn').onclick=()=>weekly(document.getElementById('pdfDate').value||isoToday())}
const s=document.createElement('style');s.textContent='#pdfTools{margin-top:14px}.pdfrow{display:grid;grid-template-columns:minmax(130px,1fr) 1fr 1fr;gap:10px;align-items:end}.pdfrow label{font-size:12px;font-weight:800;color:#687386}.pdfrow input{display:block;width:100%;margin-top:6px;box-sizing:border-box;padding:12px;border:1px solid #ccd4de;border-radius:12px;background:#fff;font-size:16px}.pdfrow button{min-height:46px}@media(max-width:600px){.pdfrow{grid-template-columns:1fr 1fr}.pdfrow label{grid-column:1/-1}}';document.head.appendChild(s);new MutationObserver(install).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});setInterval(install,700);setTimeout(install,300)
})();
