/* Relatorios PDF - Meu Treino */
(function(){
  function getPdf(){return window.jspdf&&window.jspdf.jsPDF?window.jspdf.jsPDF:null}
  function fmtDate(d){return new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})}
  function isoToday(){const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
  function mondayOf(date){const d=new Date(date+'T12:00:00'),n=d.getDay()||7;d.setDate(d.getDate()-n+1);return d.toISOString().slice(0,10)}
  function addDays(date,n){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
  function logsForDate(date){return Object.values(data?.logs||{}).filter(l=>l.date===date)}
  function volume(l){let total=0;Object.values(l?.rows||{}).forEach(r=>{for(let s=0;s<10;s++){const kg=Number(r?.['kg'+s]),reps=Number(r?.['reps'+s]);if(kg>0&&reps>0)total+=kg*reps}});return total}
  function setCount(l){let total=0;Object.values(l?.rows||{}).forEach(r=>{for(let s=0;s<10;s++)if(Number(r?.['kg'+s])>0&&Number(r?.['reps'+s])>0)total++});return total}
  function ensureSpace(doc,y,needed){if(y+needed>282){doc.addPage();return 18}return y}
  function text(doc,value,x,y,maxWidth,size){doc.setFontSize(size||10);const lines=doc.splitTextToSize(String(value||''),maxWidth||180);doc.text(lines,x,y);return y+lines.length*5}
  function header(doc,title,subtitle){doc.setFillColor(242,111,0);doc.roundedRect(12,10,186,22,4,4,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(17);doc.text('MEU TREINO',20,23);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text('MUSCULACAO • PROGRESSAO',112,23);doc.setTextColor(25,35,48);doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text(title,14,43);doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text(subtitle,14,50);return 60}
  function daily(date){const JsPDF=getPdf();if(!JsPDF){alert('O gerador de PDF ainda está carregando. Tente novamente em alguns segundos.');return}const logs=logsForDate(date),doc=new JsPDF({unit:'mm',format:'a4'});let y=header(doc,'Relatorio diario',fmtDate(date));if(!logs.length){doc.setFontSize(11);doc.text('Nenhum treino registrado nesta data.',14,y);doc.save('meu-treino-diario-'+date+'.pdf');return}logs.forEach((l,idx)=>{y=ensureSpace(doc,y,35);doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text((l.day||'Treino')+' — '+(workouts[l.day]?.title||'Treino opcional'),14,y);y+=7;doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text('Tempo: '+(l.duration||'—')+' | BPM medio: '+(l.avgBpm||'—')+' | Calorias: '+(l.calories||'—')+' | RPE: '+(l.effort||'—')+' | Volume: '+Math.round(volume(l)).toLocaleString('pt-BR')+' kg',14,y);y+=7;const ex=exFor(l.day)||[];ex.forEach((e,i)=>{const r=l.rows?.[i]||{};y=ensureSpace(doc,y,22);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text((i+1)+'. '+e[0]+' ('+e[2]+' reps)',16,y);y+=5;doc.setFont('helvetica','normal');let any=false;for(let s=0;s<e[1];s++){const kg=r['kg'+s],reps=r['reps'+s];if((kg!==undefined&&kg!=='')||(reps!==undefined&&reps!=='')){y=ensureSpace(doc,y,6);doc.text('Serie '+(s+1)+': '+(kg||'—')+' kg x '+(reps||'—')+' reps',20,y);y+=4.5;any=true}}if(r.observation){y=ensureSpace(doc,y,10);y=text(doc,'Observacao: '+r.observation,20,y,170,8)}if(!any){doc.setFontSize(8);doc.text('Sem carga/repeticoes registradas.',20,y);y+=4.5}});if(l.notes){y=ensureSpace(doc,y,15);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('Observacoes gerais',16,y);y+=5;doc.setFont('helvetica','normal');y=text(doc,l.notes,16,y,175,9)}if(idx<logs.length-1)y+=5});doc.save('meu-treino-diario-'+date+'.pdf')}
  function weekly(date){const JsPDF=getPdf();if(!JsPDF){alert('O gerador de PDF ainda está carregando. Tente novamente em alguns segundos.');return}const start=mondayOf(date),end=addDays(start,6),week=[];for(let i=0;i<7;i++){const d=addDays(start,i);week.push({date:d,logs:logsForDate(d)})}const active=week.filter(x=>x.logs.length),totalVolume=active.reduce((a,x)=>a+x.logs.reduce((b,l)=>b+volume(l),0),0),totalKcal=active.reduce((a,x)=>a+x.logs.reduce((b,l)=>b+Number(l.calories||0),0),0),totalSets=active.reduce((a,x)=>a+x.logs.reduce((b,l)=>b+setCount(l),0),0),bpmValues=active.flatMap(x=>x.logs.map(l=>Number(l.avgBpm)).filter(Boolean)),avgBpm=bpmValues.length?Math.round(bpmValues.reduce((a,b)=>a+b,0)/bpmValues.length):'—';const doc=new JsPDF({unit:'mm',format:'a4'});let y=header(doc,'Relatorio semanal',fmtDate(start)+' a '+fmtDate(end));doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('Resumo da semana',14,y);y+=7;doc.setFont('helvetica','normal');doc.setFontSize(10);y=text(doc,'Treinos realizados: '+active.reduce((a,x)=>a+x.logs.length,0),16,y,175,10);y=text(doc,'Series registradas: '+totalSets,16,y,175,10);y=text(doc,'Volume total: '+Math.round(totalVolume).toLocaleString('pt-BR')+' kg',16,y,175,10);y=text(doc,'Calorias registradas: '+Math.round(totalKcal).toLocaleString('pt-BR')+' kcal',16,y,175,10);y=text(doc,'BPM medio dos treinos com registro: '+avgBpm,16,y,175,10);y+=4;week.forEach(day=>{y=ensureSpace(doc,y,25);const l=day.logs[0];doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text(fmtDate(day.date),14,y);y+=6;if(!l){doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text('Sem treino registrado.',18,y);y+=7;return}day.logs.forEach(log=>{y=ensureSpace(doc,y,18);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text((log.day||'Treino')+' — '+(workouts[log.day]?.title||'Treino opcional'),18,y);y+=5;doc.setFont('helvetica','normal');doc.setFontSize(8.5);doc.text('Volume '+Math.round(volume(log)).toLocaleString('pt-BR')+' kg | '+setCount(log)+' series | '+(log.calories||'—')+' kcal | '+(log.avgBpm||'—')+' bpm | '+(log.duration||'—')+' | RPE '+(log.effort||'—'),18,y);y+=6;const ex=exFor(log.day)||[];ex.forEach((e,i)=>{const r=log.rows?.[i]||{},entries=[];for(let s=0;s<e[1];s++){const kg=r['kg'+s],reps=r['reps'+s];if((kg!==undefined&&kg!=='')||(reps!==undefined&&reps!==''))entries.push((kg||'—')+' kg x '+(reps||'—'))}if(entries.length){y=ensureSpace(doc,y,8);y=text(doc,(i+1)+'. '+e[0]+': '+entries.join(' | '),22,y,165,8)}})});y+=3});doc.save('meu-treino-semanal-'+start+'-'+end+'.pdf')}
  function install(){if(document.getElementById('pdfTools'))return;const h=[...document.querySelectorAll('.hero.compact h1')].find(e=>e.textContent.trim()==='Seus registros');if(!h)return;const card=h.closest('.hero.compact');if(!card)return;const box=document.createElement('section');box.id='pdfTools';box.className='card';box.innerHTML='<h2>📄 Relatorios em PDF</h2><p class="muted">Escolha uma data para gerar o relatorio daquele dia ou da semana que contem essa data.</p><div class="pdfrow"><label>Data<input id="pdfDate" type="date" value="'+isoToday()+'"></label><button class="primary" id="pdfDayBtn">PDF diario</button><button class="secondary" id="pdfWeekBtn">PDF semanal</button></div>';card.after(box);document.getElementById('pdfDayBtn').onclick=function(){daily(document.getElementById('pdfDate').value||isoToday())};document.getElementById('pdfWeekBtn').onclick=function(){weekly(document.getElementById('pdfDate').value||isoToday())}}
  const css=document.createElement('style');css.textContent='#pdfTools{margin-top:14px}.pdfrow{display:grid;grid-template-columns:minmax(130px,1fr) 1fr 1fr;gap:10px;align-items:end}.pdfrow label{font-size:12px;font-weight:700;color:#687386;text-transform:uppercase}.pdfrow input{display:block;width:100%;margin-top:6px;box-sizing:border-box;padding:12px;border:1px solid #ccd4de;border-radius:12px;background:#fff;font-size:16px}.pdfrow button{min-height:46px}@media(max-width:600px){.pdfrow{grid-template-columns:1fr 1fr}.pdfrow label{grid-column:1/-1}}';document.head.appendChild(css);const obs=new MutationObserver(install);obs.observe(document.getElementById('app')||document.body,{childList:true,subtree:true});setTimeout(install,400)
})();
