/* Meu Treino — Relatórios robustos + Coach IA */
(function(){
'use strict';
const FN='https://uvujytjdafcyacawcirp.supabase.co/functions/v1/coach-ai';
const today=()=>{const d=new Date();return d.toISOString().slice(0,10)};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function getLogs(){try{return Object.values(window.data?.logs||{}).filter(l=>l&&l.date&&!l.draft&&!l.appleFitness?.imported)}catch(e){return[]}}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function vol(l){let x=0;Object.values(l?.rows||{}).forEach(r=>{for(let s=0;s<15;s++){const k=num(r?.['kg'+s]),p=num(r?.['reps'+s]);if(k>0&&p>0)x+=k*p}});return x}
function mins(v){if(!v)return 0;const s=String(v);if(s.includes(':')){const p=s.split(':').map(Number);return p.length===3?p[0]*60+p[1]+p[2]/60:p[0]+p[1]/60}const n=num(v);return n>180?n/60:n}
function fmt(m){if(!m)return '—';m=Math.round(m);return m>=60?Math.floor(m/60)+'h '+m%60+'min':m+'min'}
function last7(ls){const n=new Date();n.setHours(0,0,0,0);const start=new Date(n);start.setDate(n.getDate()-6);return ls.filter(l=>{const d=new Date(l.date+'T12:00:00');return d>=start&&d<=n})}
function render(){
 const app=document.getElementById('app'); if(!app||window.current!=='Relatórios')return;
 if(document.getElementById('reportsFix'))return;
 const ls=getLogs(),week=last7(ls); const total=ls.length, volume=ls.reduce((a,l)=>a+vol(l),0);
 const avg=week.filter(l=>l.duration).reduce((a,l)=>a+mins(l.duration),0)/(week.filter(l=>l.duration).length||1);
 const cardio=week.filter(l=>l.cardio?.duration).reduce((a,l)=>a+mins(l.cardio.duration),0);
 const card=document.createElement('section');card.id='reportsFix';card.className='rf';
 card.innerHTML=`<div class="rf-title"><span>📈 EVOLUÇÃO</span><h2>Seu progresso</h2><p>Dados dos treinos salvos neste aparelho.</p></div>
 <div class="rf-grid"><article><small>🏋️ TREINOS</small><b>${total}</b><em>${week.length} nos últimos 7 dias</em></article><article><small>⚖️ VOLUME</small><b>${volume?Math.round(volume).toLocaleString('pt-BR'):'—'}</b><em>kg × reps acumulados</em></article><article><small>⏱️ TEMPO MÉDIO</small><b>${fmt(avg)}</b><em>musculação na última semana</em></article><article><small>🏃 CARDIO</small><b>${fmt(cardio)}</b><em>tempo nos últimos 7 dias</em></article></div>
 <div class="rf-block"><h3>🏆 Melhores marcas</h3><div id="rfRecords"></div></div>
 <div class="rf-block"><h3>📊 Evolução por exercício</h3><p>Selecione um exercício para ver a evolução da melhor carga.</p><select id="rfExercise"></select><div id="rfChart"></div></div>
 <div class="rf-block"><h3>📅 Consistência</h3><div class="rf-week">${[6,5,4,3,2,1,0].map(i=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-i);const ok=ls.some(l=>l.date===d.toISOString().slice(0,10));return `<div class="${ok?'ok':''}"><b>${d.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','')}</b><span>${ok?'✓':'·'}</span></div>`}).join('')}</div></div>
 <div class="rf-block rf-coach"><div class="rf-coach-head"><div><span>✨ COACH IA</span><h3>Análise inteligente</h3><p>Use seus registros para receber uma análise da semana.</p></div><strong>IA</strong></div><button id="rfCoachBtn">ANALISAR SEMANA COM IA</button><div id="rfCoachOut"></div></div>`;
 app.appendChild(card);
 const names=[]; const seen=new Set(); ls.forEach(l=>{const ex=window.workouts?.[l.day]?.ex||[];ex.forEach(e=>{if(!seen.has(e[0])){seen.add(e[0]);names.push(e[0])}})});
 const sel=document.getElementById('rfExercise');names.forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=n;sel.appendChild(o)});
 function hist(name){const out=[];ls.forEach(l=>{const ex=window.workouts?.[l.day]?.ex||[];const i=ex.findIndex(e=>e[0]===name);if(i<0)return;const r=l.rows?.[i]||{};let best=0;for(let s=0;s<15;s++)best=Math.max(best,num(r['kg'+s]));if(best)out.push({date:l.date,best})});return out.sort((a,b)=>a.date.localeCompare(b.date)).slice(-10)}
 function draw(name){const h=hist(name),box=document.getElementById('rfChart');if(!box)return;if(!h.length){box.innerHTML='<div class="rf-empty">Ainda não há dados suficientes.</div>';return}const mx=Math.max(...h.map(x=>x.best),1);box.innerHTML='<div class="rf-bars">'+h.map(x=>`<div><b>${x.best}</b><i style="height:${Math.max(10,x.best/mx*150)}px"></i><small>${x.date.slice(8,10)}/${x.date.slice(5,7)}</small></div>`).join('')+'</div>'}
 if(names.length){sel.value=names[0];draw(names[0])}sel.addEventListener('change',e=>draw(e.target.value));
 const best={};ls.forEach(l=>{const ex=window.workouts?.[l.day]?.ex||[];ex.forEach((e,i)=>{const r=l.rows?.[i]||{};for(let s=0;s<15;s++){const k=num(r['kg'+s]),p=num(r['reps'+s]);if(k&&p&&(!best[e[0]]||k>best[e[0]].kg||k*p>best[e[0]].score))best[e[0]]={kg:k,p,score:k*p,date:l.date}}})});
 const rec=Object.entries(best).sort((a,b)=>b[1].score-a[1].score).slice(0,8);document.getElementById('rfRecords').innerHTML=rec.length?rec.map(([n,r])=>`<div class="rf-record"><b>${esc(n)}</b><span>${r.kg} kg × ${r.p} reps</span><small>${r.date}</small></div>`).join(''):'<div class="rf-empty">Salve seus treinos para criar os recordes.</div>';
 document.getElementById('rfCoachBtn').onclick=analyze;
 async function analyze(){const btn=document.getElementById('rfCoachBtn'),out=document.getElementById('rfCoachOut');btn.disabled=true;btn.textContent='ANALISANDO...';out.innerHTML='<p>Comparando seus treinos e sua evolução...</p>';try{const client=window.sb;if(!client)throw new Error('Conexão não disponível.');const ss=await client.auth.getSession();const token=ss?.data?.session?.access_token;if(!token)throw new Error('Faça login no app para usar o Coach IA.');const r=await fetch(FN,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({day:'Relatórios',title:'Análise semanal do Meu Treino',log:{date:today(),day:'Relatórios',rows:{},cardio:{}},history:ls.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,12)})});const p=await r.json();if(!r.ok||p.error)throw new Error(p.error||'Não foi possível analisar.');const list=a=>(a||[]).map(x=>`<li>${esc(x)}</li>`).join('');out.innerHTML=`<div class="rf-score"><strong>${Number(p.score||0).toFixed(1)}</strong><span>${esc(p.headline||'Análise da semana')}</span></div><p>${esc(p.summary||'')}</p><div class="rf-coach-cols"><div><b>Pontos fortes</b><ul>${list(p.highlights)}</ul></div><div><b>Atenção</b><ul>${list(p.attention)}</ul></div></div><div class="rf-next"><b>Recomendações</b><ul>${list(p.recommendations)}</ul><p><b>Próximo treino:</b> ${esc(p.next_workout||'')}</p></div>`;btn.textContent='ATUALIZAR ANÁLISE'}catch(e){out.innerHTML='<p class="rf-error">'+esc(e.message)+'</p>';btn.textContent='TENTAR NOVAMENTE'}finally{btn.disabled=false}}
}
const css=document.createElement('style');css.textContent=`.rf{margin:18px 0 120px;padding:20px;border:1px solid #dce3e9;border-radius:22px;background:#fff;color:#17202a;box-shadow:0 8px 28px rgba(0,0,0,.06)}.rf-title span,.rf-coach-head span{font-size:13px;font-weight:900;letter-spacing:3px;color:#e56c27}.rf-title h2{margin:5px 0;font-size:28px}.rf p{color:#718096}.rf-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:18px 0}.rf-grid article{border:1px solid #dce3e9;border-radius:16px;padding:14px}.rf-grid small{display:block;color:#718096;font-weight:900}.rf-grid b{display:block;font-size:24px;margin:6px 0}.rf-grid em{font-style:normal;color:#718096;font-size:12px}.rf-block{border-top:1px solid #e3e8ed;margin-top:18px;padding-top:18px}.rf-block h3{margin:0 0 5px}.rf-record{display:grid;grid-template-columns:1fr auto auto;gap:10px;padding:10px;border:1px solid #e1e7ec;border-radius:12px;margin-top:7px}.rf-record small{color:#718096}.rf select{width:100%;padding:11px;border:1px solid #d5dde5;border-radius:11px;background:#fff;color:#17202a;margin:10px 0}.rf-bars{height:190px;display:flex;align-items:end;gap:10px;padding:15px;border:1px solid #e1e7ec;border-radius:14px;overflow-x:auto}.rf-bars>div{min-width:38px;height:170px;display:flex;flex-direction:column;align-items:center;justify-content:end;gap:3px}.rf-bars i{display:block;width:24px;background:#e86f22;border-radius:6px 6px 2px 2px}.rf-bars small{font-size:9px;color:#718096}.rf-week{display:grid;grid-template-columns:repeat(7,1fr);gap:7px}.rf-week>div{border:1px solid #dce3e9;border-radius:12px;text-align:center;padding:10px;color:#718096}.rf-week b{display:block;font-size:11px;text-transform:uppercase}.rf-week span{font-size:22px}.rf-week .ok{background:#eef8d8;border-color:#b8e450;color:#3c5810}.rf-coach{background:linear-gradient(135deg,#fff,#fff8f1);border:1px solid #f1dfd2;padding:18px;border-radius:18px}.rf-coach-head{display:flex;justify-content:space-between}.rf-coach-head h3{margin:5px 0}.rf-coach-head strong{background:#fff0e5;color:#e46b20;border-radius:50%;width:38px;height:38px;display:grid;place-items:center}.rf-coach button{width:100%;margin-top:12px;border:0;border-radius:13px;padding:13px;background:#e86f22;color:#fff;font-weight:900}.rf-score{display:flex;gap:12px;align-items:center;margin-top:15px}.rf-score strong{font-size:30px;color:#e86f22}.rf-coach-cols{display:grid;grid-template-columns:1fr 1fr;gap:12px}.rf-coach-cols>div,.rf-next{background:#f7f8fa;padding:12px;border-radius:12px}.rf-error{color:#b33131}.rf-empty{padding:14px;background:#f4f6f8;border-radius:12px;color:#718096}@media(max-width:600px){.rf-grid{grid-template-columns:1fr 1fr}.rf-record{grid-template-columns:1fr}.rf-coach-cols{grid-template-columns:1fr}}`;
document.head.appendChild(css);
let last='';function watch(){if(window.current==='Relatórios'){if(last!=='Relatórios'){document.getElementById('reportsFix')?.remove();last='Relatórios'}render()}else{last=window.current||'';document.getElementById('reportsFix')?.remove()}}
new MutationObserver(watch).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});setInterval(watch,500);window.addEventListener('load',watch);setTimeout(watch,300);
})();
