/* Meu Treino — Coach IA somente em Relatórios */
(function(){
'use strict';
const FN='https://uvujytjdafcyacawcirp.supabase.co/functions/v1/coach-ai';
const KEY='meu_treino_reset_v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{"logs":{}}')}catch(e){return{logs:{}}}}
function logs(){return Object.values(read().logs||{}).filter(l=>l&&l.date&&!l.draft&&!l.appleFitness?.imported).sort((a,b)=>String(b.date).localeCompare(String(a.date)))}
function isReports(){const app=document.getElementById('app');if(!app)return false;return [...app.querySelectorAll('.nav button,.bottomnav button')].some(b=>b.classList.contains('active')&&/Relatórios/i.test(b.textContent||''))}
function mount(){const app=document.getElementById('app');if(!app||!isReports()){document.getElementById('reportWorkoutAI')?.remove();return}if(document.getElementById('reportWorkoutAI'))return;const latest=logs()[0];if(!latest)return;const box=document.createElement('section');box.id='reportWorkoutAI';box.className='card report-ai-card';box.innerHTML='<h2>✨ Análise do treino com IA</h2><p class="muted">Analise o treino mais recente salvo no seu histórico, sem sair da aba Relatórios.</p><button id="reportWorkoutAIBtn" class="primary wide">ANALISAR TREINO COM IA</button><div id="reportWorkoutAIResult" class="report-ai-result"></div>';const reports=[...app.querySelectorAll('.card')].find(x=>/PDF|Relatórios em PDF/i.test(x.textContent||''));if(reports)reports.after(box);else app.appendChild(box);document.getElementById('reportWorkoutAIBtn').onclick=()=>analyze(latest)}
async function analyze(log){const b=document.getElementById('reportWorkoutAIBtn'),o=document.getElementById('reportWorkoutAIResult');if(!b||!o)return;b.disabled=true;b.textContent='ANALISANDO...';o.innerHTML='<div class="muted">A IA está analisando o treino mais recente...</div>';try{if(typeof sb==='undefined'||!sb)throw Error('Conexão não disponível.');const ss=await sb.auth.getSession(),token=ss?.data?.session?.access_token;if(!token)throw Error('Faça login no app para usar o Coach IA.');const title=workouts?.[log.day]?.title||log.day||'Treino';const r=await fetch(FN,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({day:log.day,title,log,history:logs().slice(0,8)})});const p=await r.json();if(!r.ok||p.error)throw Error(p.error||'Não foi possível analisar o treino.');o.innerHTML='<div class="report-ai-score">'+Number(p.score).toFixed(1)+'/10</div><b>'+esc(p.headline||'Análise do treino')+'</b><p>'+esc(p.summary||'')+'</p><div class="report-ai-cols"><div><h4>Pontos fortes</h4><ul>'+((p.highlights||[]).map(x=>'<li>'+esc(x)+'</li>').join('')||'<li>Nenhum ponto registrado.</li>')+'</ul></div><div><h4>Atenção</h4><ul>'+((p.attention||[]).map(x=>'<li>'+esc(x)+'</li>').join('')||'<li>Nenhum ponto registrado.</li>')+'</ul></div></div><h4>Recomendações</h4><ul>'+((p.recommendations||[]).map(x=>'<li>'+esc(x)+'</li>').join('')||'<li>Continue buscando progressão gradual.</li>')+'</ul><p><b>Próximo treino:</b> '+esc(p.next_workout||'Continue buscando progressão gradual.')+'</p>';b.textContent='ATUALIZAR ANÁLISE'}catch(e){o.innerHTML='<div style="color:#b33131">'+esc(e.message||'Erro ao analisar.')+'</div>';b.textContent='TENTAR NOVAMENTE'}finally{b.disabled=false}}
const s=document.createElement('style');s.textContent='.report-ai-card{background:linear-gradient(135deg,#fff8f1,#fff)}.report-ai-result{margin-top:14px;line-height:1.5;color:#46515e}.report-ai-score{font-size:30px;font-weight:900;color:#e86f22;margin-bottom:4px}.report-ai-cols{display:grid;grid-template-columns:1fr 1fr;gap:12px}.report-ai-cols>div{background:#f7f8fa;border-radius:14px;padding:10px}.report-ai-card h4{margin-bottom:5px}.report-ai-card ul{margin-top:5px}@media(max-width:600px){.report-ai-cols{grid-template-columns:1fr}}';document.head.appendChild(s);window.addEventListener('load',mount);setInterval(mount,800);new MutationObserver(mount).observe(document.getElementById('app')||document.body,{childList:true,subtree:true})
})();
