/* Meu Treino — Relatórios definitivo + Coach IA */
(function(){
'use strict';
const FN='https://uvujytjdafcyacawcirp.supabase.co/functions/v1/coach-ai';
const KEY='meu_treino_reset_v1';
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{"logs":{}}')}catch(e){return{logs:{}}}}
function logs(){return Object.values(read().logs||{}).filter(l=>l&&l.date&&!l.draft&&!l.appleFitness?.imported).sort((a,b)=>String(b.date).localeCompare(String(a.date)))}
function n(v){const x=Number(v);return Number.isFinite(x)?x:0}
function volume(l){let v=0;Object.values(l.rows||{}).forEach(r=>{for(let s=0;s<15;s++){const kg=n(r['kg'+s]),rp=n(r['reps'+s]);if(kg>0&&rp>0)v+=kg*rp}});return v}
function dur(v){if(v==null||v==='')return 0;const s=String(v);if(s.includes(':')){const p=s.split(':').map(Number);return p.length===3?p[0]*3600+p[1]*60+p[2]:p[0]*60+p[1]}const x=n(v);return x>0&&x<=180?x*60:x}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function isReports(){const app=document.getElementById('app');if(!app)return false;return [...app.querySelectorAll('.nav button,.bottomnav button')].some(b=>b.classList.contains('active')&&/Relatórios/i.test(b.textContent||''))}
function style(){if(document.getElementById('reports-final-style'))return;const s=document.createElement('style');s.id='reports-final-style';s.textContent='.rf{margin:18px 0 120px;padding:20px;border:1px solid #dce3e9;border-radius:22px;background:#fff;box-shadow:0 8px 28px rgba(0,0,0,.06)}.rf h2{margin:0;font-size:24px}.rf-sub{color:#748091;margin:5px 0 18px}.rf-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.rf-card{border:1px solid #e1e7ec;border-radius:15px;padding:14px}.rf-card small{display:block;color:#778391;font-weight:900}.rf-card b{display:block;font-size:24px;margin-top:6px}.rf-section{border-top:1px solid #e5e9ed;margin-top:18px;padding-top:16px}.rf-bars{display:flex;align-items:end;gap:8px;height:130px;margin-top:12px}.rf-bar{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:end;height:100%}.rf-bar i{display:block;width:100%;max-width:34px;background:#e86f22;border-radius:7px 7px 2px 2px;min-height:4px}.rf-bar small{font-size:9px;color:#788391;margin-top:5px}.rf-coach{background:linear-gradient(135deg,#fff8f1,#fff);border:1px solid #f0d7c3}.rf-btn{width:100%;border:0;border-radius:13px;padding:14px;background:#e86f22;color:#fff;font-weight:900;font-size:15px}.rf-result{margin-top:14px;line-height:1.5;color:#46515e}.rf-score{font-size:30px;font-weight:900;color:#e86f22}.rf-result ul{margin-top:5px}.rf-loading{color:#7a8592}@media(max-width:650px){.rf-grid{grid-template-columns:1fr 1fr}}';document.head.appendChild(s)}
function render(){if(!isReports()){document.getElementById('reportsFinal')?.remove();return}if(document.getElementById('reportsFinal'))return;style();const ls=logs();const total=ls.length,vol=ls.reduce((a,l)=>a+volume(l),0);const times=ls.map(l=>dur(l.duration)).filter(Boolean);const avg=times.length?Math.round(times.reduce((a,b)=>a+b,0)/times.length):0;const last7=ls.filter(l=>Date.now()-new Date(l.date+'T12:00:00').getTime()<7*86400000).length;const days=new Set(ls.map(l=>l.date));let streak=0,d=new Date();d.setHours(12,0,0,0);for(let i=0;i<370;i++){const k=d.toISOString().slice(0,10);if(days.has(k)){streak++;d.setDate(d.getDate()-1)}else break}const week=[];for(let i=6;i>=0;i--){const x=new Date();x.setHours(12,0,0,0);x.setDate(x.getDate()-i);week.push({d:x.toISOString().slice(0,10),label:x.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','')})}const max=Math.max(...week.map(x=>ls.filter(l=>l.date===x.d).reduce((a,l)=>a+volume(l),0)),1);const app=document.getElementById('app');app.insertAdjacentHTML('beforeend',`<section id="reportsFinal" class="rf"><h2>📈 Evolução</h2><div class="rf-sub">Dados dos treinos salvos no Meu Treino.</div><div class="rf-grid"><div class="rf-card"><small>TREINOS</small><b>${total}</b></div><div class="rf-card"><small>VOLUME</small><b>${Math.round(vol).toLocaleString('pt-BR')} kg</b></div><div class="rf-card"><small>TEMPO MÉDIO</small><b>${avg?Math.floor(avg/60)+' min':'—'}</b></div><div class="rf-card"><small>ÚLTIMOS 7 DIAS</small><b>${last7}</b></div><div class="rf-card"><small>SEQUÊNCIA</small><b>${streak} dias</b></div></div><div class="rf-section"><h3>📊 Volume por dia</h3><div class="rf-bars">${week.map(x=>{const v=ls.filter(l=>l.date===x.d).reduce((a,l)=>a+volume(l),0);const h=Math.max(4,Math.round(v/max*100));return `<div class="rf-bar"><i style="height:${h}%"></i><small>${x.label}</small></div>`}).join('')}</div></div><div class="rf-section rf-coach"><h3>✨ Coach IA</h3><div class="rf-sub">Análise inteligente da sua semana de treino.</div><button id="rfCoach" class="rf-btn">ANALISAR SEMANA COM IA</button><div id="rfCoachResult" class="rf-result"></div></div></section>`);document.getElementById('rfCoach').onclick=coach}
async function coach(){const b=document.getElementById('rfCoach'),o=document.getElementById('rfCoachResult');b.disabled=true;b.textContent='ANALISANDO...';o.innerHTML='<div class="rf-loading">A IA está analisando seus registros...</div>';try{if(typeof sb==='undefined'||!sb)throw Error('Conexão não disponível.');const ss=await sb.auth.getSession();const token=ss?.data?.session?.access_token;if(!token)throw Error('Faça login no app para usar o Coach IA.');const ls=logs().slice(0,12);const payload={day:'Semana',title:'Relatório semanal',log:{date:new Date().toISOString().slice(0,10),rows:{},duration:'',cardio:{},weekly:true},history:ls};const r=await fetch(FN,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify(payload)});const p=await r.json();if(!r.ok||p.error)throw Error(p.error||'Não foi possível analisar.');o.innerHTML=`<div class="rf-score">${n(p.score).toFixed(1)}/10</div><b>${esc(p.headline||'Análise da semana')}</b><p>${esc(p.summary||'')}</p><h4>Pontos fortes</h4><ul>${(p.highlights||[]).map(x=>'<li>'+esc(x)+'</li>').join('')}</ul><h4>Atenção</h4><ul>${(p.attention||[]).map(x=>'<li>'+esc(x)+'</li>').join('')}</ul><h4>Recomendações</h4><ul>${(p.recommendations||[]).map(x=>'<li>'+esc(x)+'</li>').join('')}</ul><p><b>Próximo treino:</b> ${esc(p.next_workout||'Continue buscando progressão gradual.')}</p>`;b.textContent='ATUALIZAR ANÁLISE'}catch(e){o.innerHTML='<div style="color:#b33131">'+esc(e.message||'Erro ao analisar.')+'</div>';b.textContent='TENTAR NOVAMENTE'}finally{b.disabled=false}}
function watch(){render();setTimeout(render,500);setTimeout(render,1500)}
window.addEventListener('load',watch);setInterval(render,800);new MutationObserver(render).observe(document.body,{childList:true,subtree:true});
})();
