(function(){
  const preset={"Abdominal máquina":60,"Pêndulo":120,"Cadeira extensora":75,"Stiff com barra ou halteres":120,"Supino inclinado com halteres":120,"Supino reto máquina":90,"Crucifixo máquina":75,"Barra fixa ou puxada neutra":120,"Remada articulada com apoio no peito":120,"Remada unilateral na polia":90,"PULLDOWN":90,"Rosca direta com barra W":75,"Rosca inclinada com halteres":75,"Rosca martelo com halteres":75,"Leg press 45°":120,"Elevação pélvica":120,"Cadeira flexora bilateral":90,"Mesa flexora":90,"Desenvolvimento máquina":90,"Elevação lateral na polia":60,"Crucifixo inverso máquina":60,"Panturrilha em pé ou no leg press":75,"Supino reto com barra":150,"Supino inclinado máquina":120,"Crossover de baixo para cima":75,"Tríceps francês unilateral na polia":75,"Tríceps barra V":75,"Tríceps testa com barra W":75,"Hack squat":120,"Flexora unilateral":90,"Remada baixa triângulo":120,"Puxada alta pronada":90,"Elevação lateral":60,"Rosca Scott máquina":75,"Tríceps corda":75,"Panturrilha":75,"Crucifixo inverso":60,"Rosca martelo":75};
  const fmt=s=>Math.floor(s/60)+':'+String(s%60).padStart(2,'0');
  const timers=new WeakMap();
  function add(card){if(card.querySelector('.mini-rest'))return;const title=card.querySelector('.exname');if(!title)return;const name=title.textContent.replace(/^\d+\.\s*/,'').trim(),secs=preset[name]||90;const box=document.createElement('div');box.className='mini-rest';box.innerHTML='<span>DESCANSO</span><b>'+fmt(secs)+'</b><button type="button">▶</button>';title.parentElement.appendChild(box);let end=0,id=null;const btn=box.querySelector('button'),out=box.querySelector('b');btn.onclick=()=>{if(id){clearInterval(id);id=null;out.textContent=fmt(secs);btn.textContent='▶';return}end=Date.now()+secs*1000;btn.textContent='⏸';id=setInterval(()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000));out.textContent=fmt(left);if(!left){clearInterval(id);id=null;btn.textContent='▶';if(navigator.vibrate)navigator.vibrate(200)}},250)};timers.set(card,true)}
  function scan(){document.querySelectorAll('.exercise').forEach(add)}
  const st=document.createElement('style');st.textContent='.mini-rest{display:inline-flex;align-items:center;gap:7px;margin-left:10px;padding:6px 8px;border:1px solid #e2e6eb;border-radius:10px;background:#f7f8fa;vertical-align:middle}.mini-rest span{font-size:8px;font-weight:800;letter-spacing:.7px;color:#7a8491}.mini-rest b{font-size:15px;color:#202733;min-width:32px}.mini-rest button{border:0;border-radius:7px;background:#fff;padding:4px 7px;color:#df6508;font-weight:800;font-size:11px}@media(max-width:600px){.mini-rest{margin-left:0;margin-top:7px;display:flex;width:max-content}}';document.head.appendChild(st);
  scan();setInterval(scan,700);
})();
